Minor filepath and folder command changes in powershell script
Chia-Network/chia-blockchain pull request #10311
Opened 2022-02-19 02:01 UTC by Nikolaj-K

I went back to a Windows 10 installation attempt from May (https://github.com/Chia-Network/chia-blockchain/pull/5158). 
This PR is now some small changes that are improvements for me, the first enables running the powershell script repeatedly, ignoring a `mkdir` "already exists" complaint, and the second is using another command for jumping back two directories, where the one currently used (with the standalone dash symbol) is only a few years old. 

Now regarding the second point, I see similar complaints on this older [StackExchange post](https://stackoverflow.com/questions/19853340/powershell-how-can-i-suppress-the-error-if-file-alreadys-exists-for-mkdir-com). I looked into the history and [Wikipedia says](https://en.wikipedia.org/wiki/PowerShell#Windows_PowerShell_5.1) 
"Microsoft later professes that this number was insufficient as PowerShell Core failed to replace Windows PowerShell 5.1 and gain traction on Windows.[[98]] It was, however, popular on Linux.[[98]])" 
I suppose my machine just had the old one. Now one could also require people to have the suitable more recent Powershell version, although maybe that's not worth for just one directory jump - you can make the call.

----

And as for my installation attempt, I didn't get it down yet. Concretely I end up with the same problem that I also found in the issues [by this guy here from June](https://github.com/Chia-Network/chia-blockchain/discussions/6602). The `daemon` file is never written to `\chia-blockchain\build_scripts\dist` and the script breaks when this `daemon` ought to be moved. I'm not sure when it should have been created during the installtion.
It also says `Unable to find "c:\users\amoog\documents\git\chia-blockchain\venv\lib\site-packages\madmax\chia_plot.exe" when adding binary and data files.`, 
although that line doesn't break the script.

Lastly (fyi), I can also report of two loggings that don't break the script, but which that guy in June didn't have (and I don't think they are related to my system). First I see 
```
ERROR: Could not find a version that satisfies the requirement miniupnpc (from versions: none)
ERROR: No matching distribution found for miniupnpc
```
upon `pip install --no-index --find-links=.\win_build\ miniupnpc`. My `winbuild` does creates `miniupnpc-2.2.2-cp39-cp39-win_amd64.whl`. Maybe it's related to a version update, I don't know.
Secondly, later I get
```574243 INFO: Loading module hook 'hook-setuptools.py' from '[...]\\chia-blockchain\\venv\\lib\\site-packages\\PyInstaller\\hooks'... [...]\chia-blockchain\venv\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.```

2022-02-19 02:46 UTC, hoffmang9 commented
We only have miniupnpc pre built for Python 3.8.

2022-07-20 14:33 UTC, cmmarslender requested changes

2022-08-09 11:00 UTC, Nikolaj-K commented on build_scripts/build_windows.ps1
> +mkdir build_scripts\win_build -ErrorAction SilentlyContinue
The link you posted currently seems to be dead. What I can say is that this sort of change was necessary to make that script run through without failure. There seemed to be no interest to make the code work on Windows, so I don't think I'll go though the install attempt again in the next few months. Feel free to directly take over any change that's helpful to other branches. Best.

2022-08-09 13:51 UTC, cmmarslender commented on build_scripts/build_windows.ps1
> +mkdir build_scripts\win_build -ErrorAction SilentlyContinue
the build_* scripts here are more for making the installers, which typically run in CI. If you are trying to just install on windows from source, I believe you'd want to just use this install script: https://github.com/Chia-Network/chia-blockchain/blob/main/Install.ps1

2022-11-22 21:29 UTC, emlowe commented
Closing PR

2022-11-22 21:29 UTC, closed without merging