Add /cat_get_unacknowledged API for accessing unknown CATs
Chia-Network/chia-blockchain pull request #10382
Opened 2022-02-23 02:05 UTC by ytx1991

This is a draft version. Unit tests will be added after there is no concern about the implementation.

2022-02-28 23:12 UTC, ojura commented
@ytx1991 great to see this incoming. I have an approved related PR waiting to be merged and is going to clash a bit with yours:

https://github.com/Chia-Network/chia-blockchain/pull/10308

Is there a chance you could rebase this on top of my branch?

2022-02-28 23:28 UTC, ytx1991 commented
> @ytx1991 great to see this incoming. I have an approved related PR waiting to be merged which is going to clash a bit with yours:
> 
> #10308
> 
> Is there a chance you could rebase this on top of my branch? An important part of #10308 is centralizing the name generation for new unknown CATs; I see you're adding another hardcoded name (`Unknown`) in this PR.

Thanks for the notification. I will, but I'm not very familiar with the git PR, is my PR blocked your merge?

2022-03-01 01:15 UTC, ojura commented
> Thanks for the notification. I will, but I'm not very familiar with the git PR, is my PR blocked your merge?

There is going to be a conflict, since both our PRs touch the same stuff, like that piece of code "if cat tail is in trusted list: create wallet for it". 

I also worked to remove hardcoded names for new unknown CATs throughout the codebase and to have one centralized place where the way to generate them is defined, and that is `CATWallet.default_wallet_name_for_unknown_cat()`. You'll be going against that by introducing a new hardcoded value, `Unknown`. So I'd appreciate if you have a look at my PR and get familiarized with the changes :)

2022-03-01 18:10 UTC, ytx1991 commented
> > Thanks for the notification. I will, but I'm not very familiar with the git PR, is my PR blocked your merge?
> 
> @ytx1991 there is going to be a conflict, since both our PRs touch the same stuff, like that piece of code "if cat tail is in trusted list: create wallet for it".
> 
> I also worked to remove hardcoded names for new unknown CATs throughout the codebase and to have one centralized place where the way to generate them is defined, and that is `CATWallet.default_wallet_name_for_unknown_cat()`. You'll be going against that by introducing a new hardcoded value, `Unknown`. So I'd appreciate if you have a look at my PR and get familiarized with the (approved!) changes :)

I read the code, I just want to wait your change merged to the main branch then rebase. If you cannot merge your change because mine, let me know.

2022-03-23 17:57 UTC, paninaro commented on chia/wallet/wallet_state_manager.py
> +                    )
```suggestion
                    )
                    self.state_changed("added_unacknowledged_token")
```

2022-03-23 22:54 UTC, paninaro approved these changes
The exposed RPC name doesn't sound quite right, but I don't have a great alternative to suggest.

Looks good to me.

2022-03-29 20:53 UTC, paninaro commented on chia/rpc/wallet_rpc_api.py
> +    async def cat_get_unacknowledged(self, request):
```suggestion
    async def get_stray_cats(self, request):
```

2022-03-29 20:53 UTC, paninaro commented on chia/rpc/wallet_rpc_api.py
> +            "/cat_get_unacknowledged": self.cat_get_unacknowledged,
```suggestion
            "/get_stray_cats": self.get_stray_cats,
```

2022-03-29 20:53 UTC, paninaro commented on chia/rpc/wallet_rpc_client.py
> +        response = await self.fetch("cat_get_unacknowledged", {})
```suggestion
        response = await self.fetch("get_stray_cats", {})
```

2022-03-29 20:54 UTC, paninaro requested changes
Suggesting the RPC name change to `get_stray_cats` since that's what people liked the most.

2022-03-30 00:15 UTC, paninaro commented on chia/wallet/wallet_state_manager.py
> +                    self.state_changed("added_unacknowledged_token")
```suggestion
                    self.state_changed("added_stray_cat")
```

2022-03-30 01:42 UTC, paninaro approved these changes

2022-04-07 16:22 UTC, merged