Rename confusing fixtures, especially ones with the same name but dif…
Chia-Network/chia-blockchain pull request #10778
Opened 2022-03-16 21:17 UTC by aqk

…ferent implementation

2022-03-16 22:25 UTC, aqk commented
Please see 

https://github.com/Chia-Network/chia-blockchain/pull/10768
https://github.com/Chia-Network/chia-blockchain/pull/10769
https://github.com/Chia-Network/chia-blockchain/pull/10770
https://github.com/Chia-Network/chia-blockchain/pull/10772

2022-03-17 03:58 UTC, xdustinface requested changes
See the two comments + i wonder why the GUI update?

2022-03-17 03:58 UTC, xdustinface commented on tests/core/full_node/stores/test_full_node_store.py
> +@pytest_asyncio.fixture(scope="function", params=[1, 2])  # xxxtest_constants_original.replace
```suggestion
@pytest_asyncio.fixture(scope="function", params=[1, 2])
```

Is this intentional?

2022-03-17 03:58 UTC, xdustinface commented on tests/core/full_node/stores/test_full_node_store.py
> +@pytest_asyncio.fixture(scope="function", params=[1, 2])  # xxxtest_constants_original.replace
```suggestion
@pytest_asyncio.fixture(scope="function", params=[1, 2])
```

Same question :)

2022-03-18 08:33 UTC, aqk commented on tests/core/full_node/stores/test_full_node_store.py
> +@pytest_asyncio.fixture(scope="function", params=[1, 2])  # xxxtest_constants_original.replace
No, that's leftover

2022-03-18 08:34 UTC, aqk commented
Thank you - the chia-blockchain-gui submodule change was because a change was introduced in github or in the node build process that caused the M1 build test to fail

2022-03-25 15:48 UTC, arvidn commented
is this PR still relevant?

2022-03-25 15:54 UTC, aqk commented
@arvidn Unfortunately, there's no reply feature like in the code conversation

The reasons it's good to have all the fixtures in `tests/conftest.py`:

* Make it easier for someone to de-duplicate
* Prevent adding duplicate fixtures pre-emptively
* efficiency later: change the scope in one place

2022-03-25 18:00 UTC, altendky submitted a review, later dismissed
Looks like some extra import changes (isort?) but it's all test files.  The changes appear to all be copy/paste and it looks like tests should break if it were wrong.  Looks like a good step towards deduping all these similar fixtures.

2022-03-28 18:38 UTC, aqk commented
@xdustinface those requested changes are addressed.

2022-03-29 17:27 UTC, altendky approved these changes

2022-03-29 18:57 UTC, xdustinface approved these changes

2022-03-29 20:25 UTC, merged