Improve handling of unknown pending balances (likely change from addi…
Chia-Network/chia-blockchain pull request #10984
Opened 2022-03-31 21:36 UTC by paninaro

…ng a maker fee).

Minor improvement for fingerprint selection -- enter/return selects the logged-in fingerprint.

2022-04-04 19:53 UTC, paninaro commented on chia/cmds/wallet_funcs.py
> +async def print_offer_summary(cat_name_resolver: CATNameResolver, sum_dict: Dict[str, int], has_fee: bool = False):
passing in `cat_name_resolver` instead of `wallet_client` makes it easier to write a unit test to test this function.

2022-04-04 19:57 UTC, paninaro commented on chia/cmds/wallet_funcs.py
> +                if index < 0 or index >= len(fingerprints):
This fixed an issue I found where you could enter `0` when selecting a key which would lead to `index == -1`

2022-04-04 20:05 UTC, paninaro commented on chia/cmds/wallet_funcs.py
> +            if asset_id == "unknown":
This is the new bit of handling for "unknown" outbound balances. We believe the amount is likely to be the returned change associated with the included fee coin(s), but we aren't 100% sure, hence the description set below.

2022-04-04 22:06 UTC, Quexington requested changes
These are great changes and well tested, but can we also remove the line from `Offer.get_pending_balances` that sets the fee as a pending balance because that line is just super broken.

2022-04-05 02:26 UTC, paninaro commented
> These are great changes and well tested, but can we also remove the line from `Offer.get_pending_balances` that sets the fee as a pending balance because that line is just super broken.

Removed the fee calculation from `get_pending_balances`. That allowed me to remove another bit of code that was filtering out the incorrect XCH pending balance.

2022-04-05 21:19 UTC, Quexington approved these changes
lgtm

2022-04-05 23:09 UTC, merged