Update peers.dat filename to handle different nets
Chia-Network/chia-blockchain pull request #11022
Opened 2022-04-03 23:29 UTC by RightSexyOrc

Propose including the net name, e.g. mainnet / testnet10 into the peers.dat file.

Lack of this has cost me hours of energy trying to switch from mainnet and sync up testnet10 and then go back.

Please test, as I haven't tested this.

Thank yee

2022-04-04 15:20 UTC, mariano54 approved these changes

2022-04-04 21:06 UTC, paninaro commented
Thanks for the suggestion -- it's a good idea. We'll need to update `peer_store_resolver.py` and the associated tests to make this work.

2022-04-04 21:14 UTC, paninaro requested changes
`peer_store_resolver.py` will need to be updated to handle this change.

2022-04-05 15:54 UTC, paninaro commented
I made some changes in a branch: [paninaro.wip_peer_store_resolver_with_challenge](https://github.com/Chia-Network/chia-blockchain/tree/paninaro.wip_peer_store_resolver_with_challenge)

Still needs a bit of testing to check upgrades, downgrades, and fresh install scenarios.

2025-10-16 21:30 UTC, closed without merging