Improved UX for plotnft claim
Chia-Network/chia-blockchain pull request #11598
Opened 2022-05-22 07:48 UTC by roybotbot

Small UX qol improvement: Makes it easier to copy the `chia wallet get_transaction` command provided after claiming plotnft rewards.

Currently, after claiming rewards this message is given:
```
Will claim rewards for wallet ID: 2.
Transaction submitted to nodes: [('825c03dee4a470e20ffebe6add2ea6e1ab05f0120ea6e596da56317a27b6e80d', 1, None)]
Do chia wallet get_transaction -f 478512361 -tx 0xc76cabfc548d85ae3c70d44788cacdf56dfc1dcd889ad2798c64753b46443655 to get status
```
One would copy the command and paste it in to check. However, when selecting, it's very easy to make the mistake of copying `to get status`after the command.

With this change, it's clear that you select everything after the colon, and you will not select any text that is not part of the command.

New message will be: 
```
To get status, use command: chia wallet get_transaction -f 478512361 -tx 0xc76cabfc548d85ae3c70d44788cacdf56dfc1dcd889ad2798c64753b46443655
```

2022-05-22 13:33 UTC, altendky commented
I don't know what you're talking about...  I've _never_ done that.  :eyes:

2022-05-22 13:36 UTC, altendky requested changes
This is a great improvement.  Large data like this is usually best to not embed inside a message.

2022-05-22 13:36 UTC, altendky commented on chia/cmds/wallet_funcs.py
> +    print(f"To get status, use command: 'chia wallet get_transaction -f {fingerprint} -tx 0x{tx_id}'")
I don't think the `'` add anything now.  Though they aren't in either of your outputs so I'm a bit confused.

```suggestion
    print(f"To get status, use command: chia wallet get_transaction -f {fingerprint} -tx 0x{tx_id}")
```

2022-05-22 15:10 UTC, mariano54 commented
Nice improvement

2022-05-23 12:36 UTC, altendky commented on chia/cmds/wallet_funcs.py
> +    print(f"To get status, use command: 'chia wallet get_transaction -f {fingerprint} -tx 0x{tx_id}'")
They should have shown in the output.

```pycon
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print(f" stuff {1} 'blue {27 + 3}' and some")
 stuff 1 'blue 30' and some
```

2022-05-23 12:36 UTC, altendky approved these changes

2022-05-25 18:35 UTC, emlowe approved these changes
Approved, really good idea!

2022-05-27 22:34 UTC, wjblanke approved these changes
aok

2022-05-31 23:25 UTC, merged