Doccie help descriptions 1
Chia-Network/chia-blockchain pull request #11661
Opened 2022-05-27 08:46 UTC by pieterhelsen

Updated the CLI's `help` command outputs to be less ambiguous in terms of which wallet to use. Specifically the help commands for `plotnft claim`, `plotnft join` and `plotnft leave`

Also updated `wallet.py` `help` commands for consistency in the use of 'Id' vs 'ID'.

2022-07-02 13:04 UTC, altendky commented
Closing momentarily to rerun with recent CI updates.

2022-07-02 13:11 UTC, altendky requested changes
Thanks for the contribution and my apologies for the delayed review here.  I definitely appreciate the improved consistency and clarity.

2022-07-02 13:11 UTC, altendky commented on chia/cmds/plotnft.py
> +    help="ID of the Pooling wallet to store pool rewards",
It feels to me like the primary consideration would be that the user is specifying the pool wallet associated with the plots they want farming for the pool.  The rewards going to that wallet seems more like an effect than a goal.

2022-07-02 13:11 UTC, altendky commented on chia/cmds/plotnft.py
> +    help="ID of the Pooling wallet currently used to store pool rewards for the plotnft",
As above.

2024-03-20 17:31 UTC, emlowe commented
Closing PR

2024-03-20 17:31 UTC, closed without merging