Confirm equality of client and server RPC routes
Chia-Network/chia-blockchain pull request #11765
Opened 2022-06-02 23:18 UTC by altendky

2022-09-22 14:34 UTC, xdustinface requested changes

2022-09-22 14:34 UTC, xdustinface commented on tests/util/rpc.py
> +    assert [only_server, only_client] == [[], []]
```suggestion
    assert {*routes_client} == {*routes_api, *routes_server}
```

Any reason to not just do the above?

2022-09-22 14:40 UTC, xdustinface commented on tests/util/rpc.py
> +    assert [only_server, only_client] == [[], []]
or maybe rather:

```suggestion
    assert sorted(routes_client) == sorted(routes_api + routes_server)
```

2022-09-23 22:32 UTC, xdustinface approved these changes

2022-09-26 16:08 UTC, emlowe approved these changes

2022-09-26 16:18 UTC, merged