Show owner pubkey as a hex string in nft list command
Chia-Network/chia-blockchain pull request #11831
Opened 2022-06-08 15:27 UTC by AmineKhaldi

2022-06-09 11:05 UTC, xdustinface requested changes
Since `owner_pubkey` is an `Optional` type, this will make `mypy` unhappy as soon as `from_json_dict` gets hinted properly like in https://github.com/Chia-Network/chia-blockchain/pull/11763/commits/f196520359cc4d083e7121220352de611ad847c4#diff-dd6f0c93f94df70ed7b9693a16d72d4d79e9f2338eb65b13bebad03b28d9593cR667

```
chia/cmds/wallet_funcs.py:773: error: Item "None" of "Optional[bytes]" has no attribute "hex"  [union-attr]
```

I guess you could add an `assert nft.owner_pubkey is not None` at the top because in this case it will probably always be set, right?

2022-06-09 12:01 UTC, xdustinface approved these changes
Looks good, but it would also fit into one line, see my suggestions :)

2022-06-09 12:07 UTC, AmineKhaldi commented on chia/cmds/wallet_funcs.py
> +                print(f"{'Owner pubkey:'.ljust(26)} {owner_pubkey}")
I tried it but that line got too long and it stood out, so I opted for the above. I don't mind either though so it's up to you guys. Thanks!

2022-06-10 20:30 UTC, wjblanke approved these changes
aok

2022-06-10 20:58 UTC, merged