added try/except for cannot start a transaction within a transaction
Chia-Network/chia-blockchain pull request #11900
Opened 2022-06-13 23:16 UTC by wjblanke

2022-06-14 02:00 UTC, altendky requested changes
pylint found us a couple things.

2022-06-14 02:00 UTC, altendky commented on chia/rpc/wallet_rpc_api.py
> +                    self.log.exception("Exception while delete_unconfirmed_transactions")
```suggestion
                    log.exception("Exception while delete_unconfirmed_transactions")
```

2022-06-15 14:46 UTC, wjblanke commented
oof 
https://github.com/Chia-Network/chia-blockchain/runs/6884329148?check_suite_focus=true#step:10:81

2022-06-15 14:47 UTC, wjblanke commented
maybe this needs a lock too
https://github.com/Chia-Network/chia-blockchain/blame/long_lived/atari/tests/pools/test_wallet_pool_store.py#L47

2022-06-22 18:34 UTC, altendky submitted a review, later dismissed

2024-01-19 16:56 UTC, closed without merging