Deduplicate pre-commit python lints from the super linter
Chia-Network/chia-blockchain pull request #12084
Opened 2022-06-25 20:41 UTC by AmineKhaldi

2022-06-26 15:19 UTC, trepca approved these changes

2022-06-26 15:25 UTC, altendky requested changes
I don't think we run pylint anywhere else so this is a removal and not a deduplication it seems.  When run elsewhere pylint ends up complaining about some stuff.

2022-06-26 16:36 UTC, altendky commented
Trying to add pylint to the regular lint run over in https://github.com/Chia-Network/chia-blockchain/pull/12100 so that this can in fact be a dedupe PR.

2022-06-27 17:14 UTC, emlowe approved these changes

2022-06-27 17:28 UTC, altendky approved these changes
Added pylint in https://github.com/Chia-Network/chia-blockchain/pull/12100 so now this is truly a dedupe/tidy pr.  Thanks!

2022-06-27 19:57 UTC, merged