Fix some more flakiness
Chia-Network/chia-blockchain pull request #12160
Opened 2022-06-30 02:43 UTC by mariano54

2022-06-30 08:45 UTC, arvidn approved these changes
did all the tests pass on the first pass with this patch? We don't really have a good metric for flakiness..

2022-06-30 09:02 UTC, mariano54 commented
> did all the tests pass on the first pass with this patch? We don't really have a good metric for flakiness..

The tests that I modified, did pass on the first try (and I ran it several times to fix other issues). 

However I saw another 4 or 5 other flaky tests that are more rare and I couldn't solve or didn't know how to solve easily. So we are a long way from full green. Some of these are:
- Farmer harvester port issue (for the tests that allocates it's port early)
- Windows file issues
- Routes do not exist for RPC server 
- File keyring OS issue

2022-06-30 12:44 UTC, altendky requested changes, later dismissed

2022-06-30 23:06 UTC, mariano54 commented on tests/wallet/test_wallet.py
> +        repeat: bool,
Oops yeah that was just to replicate the issue, will revert

2022-06-30 23:58 UTC, mariano54 commented on tests/wallet/sync/test_wallet_sync.py
> +        blocks_reorg = bt.get_consecutive_blocks(1, blocks_reorg, guarantee_transaction_block=True, current_time=True)
No, the function returns all blocks starting at height 0,always.

2022-07-01 01:02 UTC, mariano54 commented on tests/wallet/test_wallet.py
> +        repeat: bool,
This comment seems to be on an outdated commit, so it's fine i think

2022-07-01 01:08 UTC, merged