Ms.fix coin selection
Chia-Network/chia-blockchain pull request #12261
Opened 2022-07-06 06:06 UTC by mariano54

2022-07-06 16:07 UTC, emlowe commented
`valid_spendable_coins` is already sorted in descending order when passed into `select_smallest_coin_over_target` so I don't see why you are sorting it again. Same with `sum_largest_coins` - the `smaller_coin` list is already sorted in the order you need. The prior implementation logic was actually correct but with confusing parameter names.

2022-07-06 16:58 UTC, jack60612 commented
> `valid_spendable_coins` is already sorted in descending order when passed into `select_smallest_coin_over_target` so I don't see why you are sorting it again. Same with `sum_largest_coins` - the `smaller_coin` list is already sorted in the order you need. The prior implementation logic was actually correct but with confusing parameter names.

There is a bug, but it is really hard to see, so mariano simplified the logic and fixed the bug.
The increase in time is under a couple of milliseconds and it is worth the really easy to read logic in my opinion

2022-07-06 18:13 UTC, jack60612 requested changes
Just some minor test changes

2022-07-06 20:48 UTC, jack60612 commented
re running ci

2022-07-06 23:42 UTC, mariano54 commented
> `valid_spendable_coins` is already sorted in descending order when passed into `select_smallest_coin_over_target` so I don't see why you are sorting it again. Same with `sum_largest_coins` - the `smaller_coin` list is already sorted in the order you need. The prior implementation logic was actually correct but with confusing parameter names.

There was a bug when `smaller_coin_amount == len(valid_spendable_coin_list)`. I refactored that method so it's clear what it does now.

The reason I sorted within the method is that it makes the API simpler: it now no longer depends on a specific sorting. I thought that this API is harder to mess up for callers. For reference, sorting 200,000 coins in a worst case ordering takes about 0.4 seconds. This is probably OK when making a transaction, but I can see an argument either way.

2022-07-06 23:45 UTC, mariano54 commented on tests/wallet/test_coin_selection.py
> +    async def test_dust_and_one_large_coin(self, a_hash: bytes32) -> None:
Are you sure that it's exactly the same? I'm not sure about that, I rather keep both for safety

2022-07-07 00:47 UTC, mariano54 commented
@jack60612 @emlowe , take a look at the new changes.
Knapsack perf is fixed, and I reverted the sorting for more performance

2022-07-07 02:26 UTC, jack60612 commented on chia/wallet/coin_selection.py
> +        if coin_set is None or len(coin_set) > max_num_coins:
`len(coin_set) > max_num_coins` cant happen

2022-07-07 02:26 UTC, jack60612 commented on chia/wallet/coin_selection.py
> +    # sorted_coin_list: List[Coin] = list(sorted(coin_list, key=lambda c: c.amount))
remove comment

2022-07-07 02:38 UTC, jack60612 submitted a review, later dismissed
lgtm

2022-07-07 05:39 UTC, jack60612 submitted a review, later dismissed
lgtm

2022-07-07 05:41 UTC, jack60612 commented
once he fixes the lint issues i still approve it, just merge it even if i dont have the chance to re approve

2022-07-07 05:51 UTC, jack60612 approved these changes
lgtm

2022-07-07 23:50 UTC, emlowe commented on chia/wallet/coin_selection.py
> +            raise ValueError("Too many coins are required to make this transaction")
In the interest of consistency - should this be the same error text as above

` f"Transaction of {amount} mojo would use more than {max_num_coins} coins. Try sending a smaller amount"`

2022-07-07 23:50 UTC, emlowe approved these changes
Approved - minor comment on error string, but not gating

2022-07-08 01:00 UTC, merged