extend min_coin to rpc calls for coin selection
Chia-Network/chia-blockchain pull request #12274
Opened 2022-07-06 19:07 UTC by jack60612

they are passing, but no harm in being safe

2022-07-06 21:25 UTC, jack60612 commented
Manual cli tests have been successfully completed!

2022-07-06 22:13 UTC, jack60612 commented
Cat wallet support was added

2022-07-07 00:58 UTC, mariano54 requested changes
Nice change! Does this work for NFT offers also?

2022-07-07 00:58 UTC, mariano54 commented on chia/rpc/wallet_rpc_api.py
> +        min_coin_amount: uint128 = uint128(request.get("min_coin_amount", 0))
coins are uint64, but total balance can be uint128

2022-07-07 01:48 UTC, mariano54 approved these changes

2022-07-07 04:50 UTC, trepca approved these changes

2022-07-07 05:17 UTC, merged