Remove kwargs from `Service.start()`
Chia-Network/chia-blockchain pull request #12294
Opened 2022-07-08 16:29 UTC by altendky

2022-07-12 14:01 UTC, xdustinface requested changes
There is still the related parameter which the comment refers too in `WalletNode._start` https://github.com/Chia-Network/chia-blockchain/blob/280f462071e5fe1b7883cefac73712789e22b664/chia/wallet/wallet_node.py#L196

Which gets used in the wallet RPC here:

https://github.com/Chia-Network/chia-blockchain/blob/280f462071e5fe1b7883cefac73712789e22b664/chia/rpc/wallet_rpc_api.py#L209 

https://github.com/Chia-Network/chia-blockchain/blob/280f462071e5fe1b7883cefac73712789e22b664/chia/rpc/wallet_rpc_api.py#L287

https://github.com/Chia-Network/chia-blockchain/blob/280f462071e5fe1b7883cefac73712789e22b664/chia/rpc/wallet_rpc_api.py#L351


But seems like there is still no usage of the `kwargs` in `Service.start` so this PR could still be good to go in 🤔

2022-07-12 14:02 UTC, altendky commented
Apparently my searching failed, thanks.

2022-09-15 19:05 UTC, altendky commented
Yeah, I think the callee needs to keep it for the linked cases but the caller never exposes the fingerprint control.

2022-09-16 13:52 UTC, xdustinface approved these changes

2022-09-16 17:18 UTC, emlowe approved these changes

2022-09-16 21:22 UTC, merged