Expand select_coins rpc
Chia-Network/chia-blockchain pull request #12360
Opened 2022-07-13 21:15 UTC by jack60612

add min_coin_amount & excluded_coins

2022-07-14 07:52 UTC, mariano54 requested changes
LGTM! the only thing is we need a test for these, checkout `test_wallet_rpc.py`

2022-07-14 20:14 UTC, jack60612 commented
Tests added.

2022-07-15 00:31 UTC, mariano54 approved these changes

2022-07-16 01:41 UTC, wjblanke approved these changes
excluded coins!

2022-07-16 01:50 UTC, merged