Add more changes to allow for Simulator GUI
Chia-Network/chia-blockchain pull request #12703
Opened 2022-07-31 02:23 UTC by jack60612

2022-08-03 16:45 UTC, trepca submitted a review, later dismissed

2022-08-04 07:05 UTC, mariano54 requested changes

2022-08-04 07:05 UTC, mariano54 commented on chia/consensus/network_type.py
> +    SIMULATOR = 2
Alternatively, we can use the GENESIS_CHALLENGE

2022-08-04 07:10 UTC, mariano54 commented on chia/consensus/network_type.py
> +    SIMULATOR = 2
Or even better, `selected_network`, see this PR:
https://github.com/Chia-Network/chia-blockchain/pull/12783/files

2022-08-04 07:21 UTC, mariano54 commented on chia/wallet/wallet_state_manager.py
> +            return True  # sim always true if we have a genesis block
synced*

2022-08-04 15:44 UTC, jack60612 commented on chia/consensus/network_type.py
> +    SIMULATOR = 2
> Or even better, `selected_network`, see this PR: https://github.com/Chia-Network/chia-blockchain/pull/12783/files

I thought you said not to do that, but thats what i was going to originally do.

2022-08-05 04:55 UTC, mariano54 approved these changes

2022-08-05 06:23 UTC, merged