Change 'series' to 'edition'
Chia-Network/chia-blockchain pull request #12763
Opened 2022-08-03 05:48 UTC by DrakoPensulo

Change 'series_total' to 'edition_count' and 'series_number' to 'edition_number'

Make the changes consistent in the whole code.

2022-08-03 06:52 UTC, DrakoPensulo commented
The file tests\wallet\nft_wallet\test_nft_wallet.py needs to be updated so that more checks are successful.

2022-08-05 21:08 UTC, paninaro commented
This will require an update in the GUI

2022-08-05 21:30 UTC, paninaro commented
Generally we try to avoid maintain RPC backward compatibility. This change updates the RPC responses for `nft_get_nfts` and `nft_get_info` such that the `series_total`/`series_number` fields are replaced by their edition counterparts. Since other community developers may be impacted by this, we could either maintain backward compatibility by making the `edition_*` fields additive, or informing the community devs of this breaking change. I'll leave it to @trepca and @wjblanke to weigh in.

2022-08-10 12:00 UTC, wriches requested changes

2022-08-10 12:07 UTC, wriches commented on chia/cmds/wallet.py
> +@click.option("-ec", "--edition-count", help="NFT edition total, defaults to 1", type=int)
Done

2022-08-10 12:07 UTC, wriches commented on chia/cmds/wallet.py
> +    edition_total = edition_count
Done

2022-08-13 18:00 UTC, jack60612 commented on chia/cmds/wallet.py
> +@click.option("-ec", "--edition-count", help="NFT edition total, defaults to 1", type=int)
ah i did not want to change more if possible

2022-08-13 20:41 UTC, jack60612 approved these changes
lgtm

2022-08-15 18:53 UTC, wallentx commented
Hi @DrakoPensulo, thanks for the PR. I believe we had already gotten this resolved in our release branch, whose changes haven't made it into main just yet, but will do so soon with one of our checkpoint PRs.
https://github.com/Chia-Network/chia-blockchain/commit/af60a81c92cba51c650ad9a2fd2bf653efcbaf0e
I just wanted to verify with you that our changes had addressed all of the areas that were the intent of your PR before closing this. Even if we do close this one, I'd be happy to give you a shout-out in our coming release for your contribution effort.

2022-08-15 19:36 UTC, DrakoPensulo commented
Hi @wallentx . The changes in https://github.com/Chia-Network/chia-blockchain/commit/af60a81c92cba51c650ad9a2fd2bf653efcbaf0e look good to me. That is what I intended. Thank you.

2022-08-15 19:40 UTC, closed without merging