add delayed pool config update feature
Chia-Network/chia-blockchain pull request #12796
Opened 2022-08-05 00:50 UTC by jack60612

Now that our wallet can sync faster I think this a simple and easy change.
This has not been locally tested yet, but once I do have a chance to test it i will undraft it.
This closes https://github.com/Chia-Network/chia-blockchain/issues/12631

2022-08-05 00:51 UTC, jack60612 commented
replaces #12642

2022-08-05 02:20 UTC, jack60612 commented
Tested on my personal farmer, works perfectly

2022-08-05 04:46 UTC, mariano54 requested changes
Let's say you're syncing, then you sync up to the pool wallet on chain, so it get's queued up (but not written to disk) then you shut down the wallet and farmer before sync is done. 
When you start it back up, the pool config will be stuck in the old state permanently

2022-08-17 22:42 UTC, mariano54 approved these changes

2022-08-17 23:22 UTC, merged