util: Force keyring migration / Deprecate legacy keyring support
Chia-Network/chia-blockchain pull request #12801
Opened 2022-08-05 12:53 UTC by xdustinface

After this PR the users will be forced to migrate their keyring if they didn't yet. This will happen on CLI as well as on the daemon interface and wallet RPC interface. 

On the CLI the user will see the below whenever they run any `chia <command>`: 

```
Legacy keyring support is deprecated and gets removed in version 1.5.2, you need to migrate your keyring
to continue using chia.

Your existing keys will be migrated to a new keyring that is optionally secured by a master passphrase.
Would you like to set a master passphrase now? Use 'chia passphrase set' to change the passphrase.
```

Aborting the migration will result in the CLI exiting with:

```
Migration aborted, can't continue running any chia command.
```

The daemon and wallet RPC interface will respond with the below for all keychain related endpoints. Exceptions here are the daemon endpoints `keyring_status` and `migrate_keyring`  and `notify_keyring_migration_completed` as i assume they are needed for the GUI migration?

```
{
    "success": False,
    "error": "Legacy keyring support is deprecated and gets removed in version 1.5.2, "
    "you need to migrate your keyring to continue using chia.",
}
```

I tested all of this for both migration paths on the CLI. However, on the daemon/wallet interface the errors are only thrown if the legacy keyring is still mainly used, not in the case where it's only "partially migrated / unmigrated key in the legacy keyring left". I don't get though why someone would end up with this case so maybe it's just fine. Otherwise we probably need to add a check there if a partial migration is required, let me know.

2022-08-05 17:58 UTC, jack60612 commented on chia/util/keyring_wrapper.py
> +            exit("Migration aborted, can't continue running any chia command.")
maybe this can be changed to `"Migration aborted, can't run any chia commands."`

2022-08-05 18:02 UTC, jack60612 requested changes
mostly looks good, what happens if we run the ci without that flag?

2022-08-05 18:10 UTC, jack60612 commented
> mostly looks good, what happens if we run the ci without that flag?

i tested ci without flag and it all passes, so can we not include that change?

2022-08-05 19:01 UTC, xdustinface commented
> i tested ci without flag and it all passes, so can we not include that change?

Thanks, there were indeed some redundant flag additions left because i initially forced the migration for all `chia` commands, now it's just a subset on a subset and in this test it's now required for all `chia keys` calls.

2022-08-06 05:33 UTC, jack60612 commented
ci

2022-08-06 05:36 UTC, jack60612 requested changes, later dismissed
still just a small nitpick

2022-08-06 05:36 UTC, jack60612 commented on tests/core/cmds/test_keys.py
> +            [
you need to restore the old formatting

2022-08-06 05:36 UTC, jack60612 commented on tests/core/cmds/test_keys.py
> +            [
same thing

2022-08-06 05:36 UTC, jack60612 commented on tests/core/cmds/test_keys.py
> +            [
again

2022-08-06 05:36 UTC, jack60612 commented on tests/core/cmds/test_keys.py
> +            [
another one here. I won't mark any more because that would be kinda dumb but please fix all of them.

2022-08-07 19:14 UTC, wallentx commented
@xdustinface if this is intended to be in the 1.5.1 release, please target the `release/1.5.1` branch

2022-08-08 20:34 UTC, paninaro commented on chia/cmds/keys_funcs.py
> +        "\nLegacy keyring support is deprecated and is getting removed in version 1.5.2, "
```suggestion
        "\nLegacy keyring support is deprecated and will be removed in version 1.5.2. "

2022-08-08 20:34 UTC, paninaro commented on chia/cmds/keys_funcs.py
> +        "you need to migrate your keyring to continue using chia."
```suggestion
        "You need to migrate your keyring to continue using Chia."
```

2022-08-08 20:40 UTC, paninaro approved these changes, later dismissed
lgtm

2022-08-08 20:58 UTC, paninaro approved these changes
lgtm

2022-08-08 23:22 UTC, merged