Change the pattern for running pre-commit. Previously, this was using…
Chia-Network/chia-blockchain pull request #12891
Opened 2022-08-10 16:17 UTC by pmaslana

… a deprecated action workflow.

2022-08-10 18:55 UTC, altendky requested changes

2022-08-10 18:55 UTC, altendky commented on .github/workflows/pre-commit.yml
> +        pip install pre-commit
This shouldn't be needed due to:

https://github.com/Chia-Network/chia-blockchain/blob/6d605ae2119aadcfb9269f0e103d294f87d9d064/setup.py#L45

```suggestion
```

2022-08-10 19:51 UTC, altendky approved these changes

2022-08-12 19:06 UTC, cmmarslender approved these changes

2022-08-17 05:27 UTC, mariano54 approved these changes

2022-08-17 06:00 UTC, merged