add royalty calculation method and RPC
Chia-Network/chia-blockchain pull request #13129
Opened 2022-08-23 20:27 UTC by Quexington

https://github.com/Chia-Network/chia-blockchain/issues/12836

2022-08-23 20:42 UTC, Quexington commented
Example request:
```
{
  "royalty_assets": [
    {
      "asset": "0xabc...",
      "royalty_address": "0x123...",
      "royalty_pts": 5000,
    },
  ],
  "fungible_assets": [
    {
      "asset": 1,  # can be wallet ID or hex or whatever, it's not going to be used or edited
      "amount": 200,
    }
  ],
}
```
Example response:
```
{
  "0xabc...": [
    {
      "asset": 1,
      "address": "0x123...",
      "amount": 100,
    },
  ],
}
```

2022-08-24 14:39 UTC, trepca commented
Do CLI trading commands need to be updated to use this too or is that already using the underlying backend?

2022-08-24 14:42 UTC, Quexington commented
> Do CLI trading/offer commands need to be updated to use this too or is that already using the underlying backend?

I don't think there's really any CLI around royalties right now just a warning.  We could certainly improve on that.

2022-08-24 17:37 UTC, paninaro commented on chia/rpc/wallet_rpc_client.py
> +                {"asset": id, "royalty_address": royalty_info[0], "royalty_pts": royalty_info[1]}
Can we rename `royalty_pts` to `royalty_percentage` to be consistent with the existing field in nft_info?

2022-08-24 18:36 UTC, paninaro requested changes
Looks good. Just the one request to rename `royalty_pts`

2022-08-24 20:32 UTC, Quexington commented
@paninaro I fixed your comment, but also added another commit for fixing the CLI related to what @trepca said as well

2022-08-24 21:22 UTC, paninaro approved these changes, later dismissed
lgtm

2022-08-25 12:26 UTC, trepca approved these changes

2022-08-26 00:17 UTC, merged