Add a workflow for scanning python deps
Chia-Network/chia-blockchain pull request #13227
Opened 2022-08-29 18:07 UTC by pmaslana

2022-08-31 15:57 UTC, cmmarslender requested changes

2022-08-31 15:57 UTC, cmmarslender commented on .github/workflows/snyk-python-scan.yml
> +name: 🚨 Snyk Python Scan
```suggestion
name: 🚨 Snyk Python Scan
```

2022-08-31 15:57 UTC, cmmarslender commented on .github/workflows/snyk-python-scan.yml
> +  cancel-in-progress: false
Why not cancel in progress runs on the same branch like we do everywhere else in this repo?

2022-08-31 16:12 UTC, cmmarslender approved these changes, later dismissed

2022-09-30 16:44 UTC, emlowe approved these changes, later dismissed

2022-09-30 18:48 UTC, altendky commented on .github/workflows/snyk-python-scan.yml
> +    - cron: '0 0 * * 3'
@pmaslana, should this follow the standard pattern (plus cron)?

https://github.com/Chia-Network/chia-blockchain/blob/939b129f9f72dc3ee2aea0498c22363fac16e141/.github/workflows/test.yml#L3-L13

2022-11-01 15:57 UTC, altendky commented on .github/workflows/snyk-python-scan.yml
> +     - '**'
Remove extra leading space.

```suggestion
on:
  push:
    branches:
    - long_lived/**
    - main
    - release/**
    tags:
    - '**'
  pull_request:
    branches:
    - '**'
  workflow_dispatch: null
```

2022-11-14 19:45 UTC, altendky approved these changes
If this was waiting on my approval, my apologies for letting it sit around so long.  `:[`  Might be worth a daily scheduled run?  We generally run _something_ more often than that anyways so perhaps it is pointless, but it's also probably minimal extra load too.

I haven't looked through the results of this or checked to make sure it triggers emails or...  If I need to review that for this as well, let me know.

2022-11-18 16:28 UTC, emlowe approved these changes

2022-11-18 16:42 UTC, merged