Add DID sign message API
Chia-Network/chia-blockchain pull request #13269
Opened 2022-09-01 02:59 UTC by ytx1991

Follow the CHIP0002 standard

2022-09-02 16:39 UTC, Quexington requested changes

2022-09-02 16:39 UTC, Quexington commented on chia/wallet/did_wallet/did_wallet.py
> +            )
The wallet should be returning `Tuple[G1Element, G2Element]` and the RPC should convert to strings if it so desires.

2022-09-02 16:39 UTC, Quexington commented on chia/wallet/did_wallet/did_wallet.py
> +    async def sign_message(self, hex_message: str) -> Tuple[str, str]:
Take `bytes` as a message, not `str`

2022-09-02 16:39 UTC, Quexington commented on chia/wallet/did_wallet/did_wallet.py
> +                hex_message = hex_message[2:]
Use `bytes32.from_hexstr()`

2022-09-07 16:47 UTC, ytx1991 commented on chia/wallet/did_wallet/did_wallet.py
> +                hex_message = hex_message[2:]
It's not bytes32

2022-09-07 20:15 UTC, Quexington approved these changes

2022-09-13 16:44 UTC, trepca approved these changes

2022-09-13 21:08 UTC, merged