DL: stop using fee config setting and remove from initial config
Chia-Network/chia-blockchain pull request #13374
Opened 2022-09-07 21:45 UTC by emlowe

Stop using DataLayer fee setting in config and remove the setting from the initial config. Note any previous installs will still have a fee setting, but it is ignored

2022-09-08 15:12 UTC, altendky requested changes
Need to discuss with Michael.

2024-03-26 16:28 UTC, altendky approved these changes

2024-03-27 03:35 UTC, TheLastCicada approved these changes
I think this is the right way to go.  No known datalayer apps rely on the default fee.

2024-03-27 05:08 UTC, wjblanke approved these changes
aok

2024-03-27 16:10 UTC, merged