server: Make `ChiaServer` a `dataclass`
Chia-Network/chia-blockchain pull request #13574
Opened 2022-09-29 23:30 UTC by xdustinface

Based on:
- #13513 
- #13515 
- #13545 
- #13573

2022-10-10 14:10 UTC, altendky requested changes
Otherwise looks good, thanks.

2022-10-10 14:10 UTC, altendky commented on chia/server/server.py
> +            log=logging.getLogger(__name__),
?

```suggestion
            log=log,
```

2022-10-10 16:40 UTC, altendky approved these changes

2022-11-03 16:23 UTC, arvidn approved these changes

2022-11-03 16:28 UTC, merged