Freebsd improvements when checking for legacy key
Chia-Network/chia-blockchain pull request #13666
Opened 2022-10-19 18:55 UTC by seanvetter

Issue: #13282 Optional[Credential] = keyring.get_credential(keychain_service, current_user) -> AttributeError: 'NoneType' object has no attribute 'get_credential'

Freebsd platform fails to migrate in previous releases or in 1.5.1+ versions it fails to start farmer because there is a NoneType object from keyring.get_credential. This just checks for that when trying to set the legacy_keyring.

2022-10-24 16:08 UTC, emlowe approved these changes

2022-10-24 18:41 UTC, xdustinface requested changes
So this just silently ignores the legacy keyring on systems which aren't supported it seems, lets maybe just merge #13398 instead now that we have the 1.6.1 release branch? @paninaro thoughts?

2022-10-24 21:59 UTC, xdustinface reviewed
Actually, let's maybe retarget this to the 1.6.1 release branch?

2022-10-24 22:07 UTC, emlowe commented
1.6.1 is pretty set now. I see, if we merge in 13398 to main, this small fix becomes moot. I might be inclined to take it anyway in main.

2022-10-25 09:09 UTC, xdustinface approved these changes

2022-10-25 09:09 UTC, xdustinface commented
I mean yeah, the related code will be gone then, but sure, we can merge this if you wish.

2022-10-25 21:46 UTC, merged