Updating old reference to chia peer -a
Chia-Network/chia-blockchain pull request #13710
Opened 2022-10-26 02:53 UTC by wallentx

Updating the cli command reference in the output when no initial chain is found:
```
Searching for an initial chain

You may be able to expedite with 'chia show -a host:port' using a known node.

Blockchain has no blocks yet
```

2022-10-26 03:02 UTC, hoffmang9 submitted a review, later dismissed
lgtm

2022-10-26 09:15 UTC, xdustinface requested changes
`chia peer` also requires the service you want to manage.

2022-10-26 09:15 UTC, xdustinface commented on chia/cmds/show_funcs.py
> +        print("You may be able to expedite with 'chia peer -a host:port' using a known node.\n")
```suggestion
        print("You may be able to expedite with 'chia peer full_node -a host:port' using a known node.\n")
```

2022-10-27 00:12 UTC, jack60612 reviewed
refer to xdustinface's comment

2022-10-27 00:30 UTC, xdustinface approved these changes

2022-10-27 00:33 UTC, jack60612 approved these changes

2022-10-27 15:26 UTC, emlowe approved these changes

2022-10-28 21:04 UTC, merged