server: Enable and fix `mypy` for the most `chia.server` files
Chia-Network/chia-blockchain pull request #13990
Opened 2022-11-23 07:29 UTC by xdustinface

This removes the most `mypy` exceptions from `chia.server`. All but `node_discovery.py` but i will still fix this separately since its a bit more involved and will come with few PRs.

2022-11-25 18:03 UTC, altendky requested changes

2022-11-25 18:03 UTC, altendky commented on chia/types/peer_info.py
> +            raise ValueError("PeerInfo.host is not a ip address")
```suggestion
            raise ValueError("PeerInfo.host is not an ip address")
```

2022-11-27 03:00 UTC, xdustinface commented on chia/server/introducer_peers.py
> +            return NotImplemented
Added ignores in 12a5dc089021c880a4d418741f958c4c8984781a. Btw, i was just following the `mypy` recommendation which came up when i tried to hint it as `VettedPeer` :) 

```
chia/server/introducer_peers.py:33: error: Argument 1 of "__eq__" is incompatible with supertype "object"; supertype defines the argument type as "object"  [override]
chia/server/introducer_peers.py:33: note: This violates the Liskov substitution principle
chia/server/introducer_peers.py:33: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
chia/server/introducer_peers.py:33: note: It is recommended for "__eq__" to work with arbitrary objects, for example:
chia/server/introducer_peers.py:33: note:     def __eq__(self, other: object) -> bool:
chia/server/introducer_peers.py:33: note:         if not isinstance(other, VettedPeer):
chia/server/introducer_peers.py:33: note:             return NotImplemented
chia/server/introducer_peers.py:33: note:         return <logic to compare two VettedPeer instances>
```

2022-11-27 04:24 UTC, xdustinface commented
Also pushed [a262cc6](https://github.com/Chia-Network/chia-blockchain/pull/13990/commits/a262cc6b321cdb72cadd0189ef1abae370995b1a) here now after #14000 was merged.

2022-11-28 15:45 UTC, altendky commented on chia/server/introducer_peers.py
> +            return NotImplemented
Yeah, this may have been what we want.  I just didn't want to figure it out here.

2022-11-28 15:49 UTC, altendky requested changes

2022-11-28 15:49 UTC, altendky commented on chia/server/node_discovery.py
>  from random import Random
Pick one of the import styles for `random`.

2022-11-28 16:47 UTC, altendky approved these changes

2022-11-28 17:52 UTC, arvidn approved these changes

2022-11-29 00:00 UTC, merged