Add Arch Linux to install-gui.sh script
Chia-Network/chia-blockchain pull request #14059
Opened 2022-12-06 02:46 UTC by DaOneLuna

Install-gui.sh will now install nodejs and npm on Arch Linux

To Allow Arch Linux to use the install-gui script when npm or nodejs is not installed

The script will exit and the gui will not install
https://github.com/Chia-Network/chia-blockchain/issues/13719

Npm and NodeJS Will install, allowing the GUI install to continue

No

Tested manually on Arch linux

2022-12-07 16:32 UTC, ChiaMineJP requested changes

2022-12-07 17:18 UTC, DaOneLuna commented on install-gui.sh
> +      sudo pacman -Sy nodejs npm
Done

2022-12-07 22:20 UTC, ChiaMineJP approved these changes
lgtm

2022-12-09 08:42 UTC, wallentx approved these changes
This is more of a comment toward `install.sh`/`install-gui.sh` in general, rather than the proposed changes in this PR:
As an Arch user, I feel that it's not really polite behavior for scripts to exec sudo, or install anything without prompting the user, but this does seem to be in line with the expectation that we've set for all other distros.. So I'll give my approval.
My preference would be to let me know that I'm missing a dependency, and `exit 1`, so that I may have my choice as to _how_ I'd like to install the dependency.
I suppose I'm basically describing the AUR.

2022-12-09 08:48 UTC, hoffmang9 commented
The problem with your preference @wallentx is that - though it works great for you - it begs for people who aren't as sophisticated to submit support questions about why the install didn't just work. This is better these days as most install with some sort of packaged installer - but it is still a real problem with the view that install.sh should cater only to the sophisticated user

2022-12-09 09:01 UTC, wallentx commented
I fully agree that this makes for a better product, and user experience @hoffmang9.
Take my comments as nothing more than me toeing the line of Arch being antithetical to luxuries such as "easy", or "usable" 😝

2022-12-09 21:54 UTC, paninaro approved these changes
Thank you for the contribution, @DaOneLuna!

2022-12-10 02:29 UTC, merged