pools: Fix delayed pool config updates
Chia-Network/chia-blockchain pull request #14083
Opened 2022-12-08 12:04 UTC by xdustinface

We are in a DB write transaction when we are inside `apply_state_transition` where we then create a new task which fetches the plotnft state from the database. Now, if the wallet is already synced / if we call the update https://github.com/Chia-Network/chia-blockchain/blob/2dea800491302b06f555cbc545607d184f5ea1e6/chia/pools/pool_wallet.py#L321 before the DB transaction was closed we don't get the latest plotnft state since its not yet committed to the DB.  9771183265df2957cac0baa3dce5cfa9bb29851b fixes this by creating the config dict within the same task which has the write transaction open so that we get the latest data still and then it puts it into the task.

2aced3ca39a9b66c62ed8b5c747e762dd7ce073b adds a test and the other commits are some cleanups while at it.

2022-12-08 13:16 UTC, jack60612 commented
this fix looks good, i'm going to test it shortly.

2022-12-08 13:53 UTC, xdustinface commented
I think there is a issue/race now with multiple wallets because of the way the delayed update fetches the config upfront now but im on mobile, cant check for the next few hours.

2022-12-08 19:27 UTC, emlowe requested changes

2022-12-08 19:27 UTC, emlowe commented on chia/pools/pool_wallet.py
> +        if self.wallet_state_manager.synced():
This needs an await
```suggestion
        if await self.wallet_state_manager.synced():
```

2022-12-09 22:52 UTC, jack60612 commented
Closed in favor of removing offending code #14090

2022-12-09 22:52 UTC, closed without merging