It is okay to return a result in some cases when median == -1
Chia-Network/chia-blockchain pull request #14285
Opened 2023-01-05 23:01 UTC by aqk

Fixes an issue where we were too conservative in returning fee estimator results.

2023-01-06 16:56 UTC, emlowe submitted a review, later dismissed

2023-01-06 20:19 UTC, wallentx commented
@aqk All of the Fee Estimation tests seem to be failing

2023-01-09 21:33 UTC, wallentx requested changes
@aqk All of the Fee Estimation tests seem to be failing

2023-01-13 00:26 UTC, wallentx approved these changes, later dismissed

2023-01-13 20:07 UTC, emlowe approved these changes

2023-01-13 22:09 UTC, merged