Extend sign API to support hex string
Chia-Network/chia-blockchain pull request #14448
Opened 2023-01-31 19:38 UTC by ytx1991

### Purpose:
To simplify the Chialisp code using sign API, we need to support signing hex message.

### Current Behavior:
The message will be regarded as a normal string.

### New Behavior:
If the is_hex = true then the message will be convert to bytes

### Testing Notes:
unit test

2023-02-10 10:25 UTC, trepca requested changes

2023-02-10 10:25 UTC, trepca commented on chia/rpc/wallet_rpc_api.py
> +            request["message"], puzzle_hash, request.get("is_hex", is_hex)
shouldn't `request.get("is_hex", is_hex)` be just `is_hex` ?

2023-02-10 10:25 UTC, trepca commented on chia/rpc/wallet_rpc_api.py
> +                request["message"], target_nft, request.get("is_hex", False)
this needs to be sanitized too

2023-02-10 10:26 UTC, trepca commented on tests/wallet/test_wallet.py
> +            {"address": encode_puzzle_hash(ph, "xch"), "message": message, "is_hex": True}
please add tests with badly formed `is_hex` parameter too

2023-02-20 17:05 UTC, trepca approved these changes

2023-02-22 18:19 UTC, altendky commented
Note that discussions need to be resolved.

2023-02-24 03:52 UTC, merged