No need to test install scripts on Mint
Chia-Network/chia-blockchain pull request #14536
Opened 2023-02-09 18:04 UTC by emlowe

Testing the install scripts on Linux Mint has very little value and simply causes longer CI times along with more chances of flaky failure due to network issues during OS setup.

We are transitioning away from users running the install manually to more and more encouraging users to use the binary packages and Mint users can use the Ubuntu DEB package.

This distro is only minimally popular and there is no rationale for specific testing on Mint as opposed to other distros (Gentoo, etc)

2023-02-09 18:41 UTC, altendky requested changes
As long as we are agreeing to not fix issues with source installs on Mint, alrighty.  Though supporting a platform but not supporting it for source leaves you in a position where you just sorta make guesses, wait for a build, and check the output since you can't source install.  So maybe we should just make Mint entirely unsupported?  Also, is there any code left in `install.sh` that is meant for Mint?  It should probably get removed.

2023-02-09 19:54 UTC, emlowe commented
There are any number of ubuntu-based distros that likely work with the packaged installer. We don't have to call out that we don't support them and we don't have to call out we do support them. We don't list Mint specifically anywhere as working in our wiki or docs.

There is only one minor reference to Mint in the install.sh script which explains why we use "20" instead of "20.04" in a version check - this is hardly worth changing.

2023-02-12 16:23 UTC, altendky approved these changes
I don't know about the others, but Mint now deviates even more than before with Mint 21 coming from Ubuntu 22 or something.  If we're dropping testing here for this awkward flavor of Ubuntu then I expect us to not maintain logic for the source install to work there.

2023-02-28 09:10 UTC, wallentx approved these changes

2023-04-11 15:13 UTC, trepca approved these changes

2023-04-11 20:56 UTC, merged