Make sure to await properly during Daemon shutdown
Chia-Network/chia-blockchain pull request #14663
Opened 2023-02-23 23:08 UTC by emlowe

Running a simple test like `test_daemon_rpc` with `pytest -n 0 tests/core/test_daemon_rpc.py` results in various not awaited errors and task destroyed messages like :
```
sys:1: RuntimeWarning: coroutine 'WebServer._close' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<WebServer._close() running at /Users/elowe/source/chia-blockchain/chia/util/network.py:91> cb=[Task.task_wakeup()]>
```

The daemon stop method creates a task to call `self.exit()` but then never awaits that task.

Since the stop method is already async, it seems easier to directly `await self.exit()` rather than create a task for it

With this change, the test above exits cleanly without errors

2023-02-24 03:45 UTC, xdustinface requested changes
This is a problem because you are with this waiting for the server to shutdown during processing the `exit` message which runs inside `incoming_connection` which runs as part of the server context. So this `await` you added leads to some weird "the task waits inside itself for itself to be done" situation i think?

You can see if you try to stop the daemon via `chia stop all -d`, it will fail with a timeout or open/close the GUI, it will stuck because there will no more response from the daemon.

2023-02-24 18:20 UTC, emlowe commented
Yea, daemon shutdown is messy and agreed this isn't the correct way to solve it. Although it does make the tests cleanup correct. But the current code also isn't great since it just creates the task and never awaits it. I'll move to draft to explore other options

2023-02-24 20:33 UTC, emlowe commented
Latest commit I think works in a variety of tests I have done.

2023-02-25 05:26 UTC, xdustinface requested changes
Seems to work with this now but while reviewing i realised we can actually just do https://github.com/Chia-Network/chia-blockchain/pull/14674.

2023-02-28 18:44 UTC, emlowe commented
Closing PR as was replaced by https://github.com/Chia-Network/chia-blockchain/pull/14674.

2023-02-28 18:44 UTC, closed without merging