work around issue in Python 3.9 import
Chia-Network/chia-blockchain pull request #14717
Opened 2023-03-02 06:49 UTC by aqk

### Purpose:

### Current Behavior:

### New Behavior:

### Testing Notes:

2023-03-02 09:45 UTC, arvidn approved these changes

2023-03-02 14:09 UTC, altendky requested changes
Can we chat about this?

2023-03-02 19:58 UTC, emlowe commented
As an FYI, setproctitle was updated recently to 1.3.2 in https://github.com/Chia-Network/chia-blockchain/pull/13920

2023-03-06 18:47 UTC, aqk commented
Hey, this PR was started because I didn't understand how module in our code was being implicitly included in our include namespace. Kyle explained what is happening here.

This is an issue where Python auto-adds files in your local directory to your import path, possibly conflicting with the toplevel imports in Python's stdlib.

Happens if you are in the directory with a file that uses the same name of a module in the stdlib.

We'll try to find another way to work around this confusing behaviour.

2023-03-06 18:47 UTC, closed without merging