avoid ValueErrors when FullNode.fetch_block_batches() when removing already removed peer
Chia-Network/chia-blockchain pull request #14803
Opened 2023-03-11 13:41 UTC by altendky

### Purpose:

### Current Behavior:

### New Behavior:

### Testing Notes:

2023-03-13 06:35 UTC, xdustinface requested changes
Hm, looking at the surrounding code this removal and the usage of `peers_with_peak ` seems strange to begin with. We remove from `peers_with_peak` which is created outside the task and not longer used anywhere else because we copy it into `new_peers_with_peak` in the task https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1070
Yes its "used" in the validation task to remove peers but this doesn't really make sense imo. I think we can also just drop those two lines?
https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1117-L1118
It seems its enough to just close the connection there, what we already do https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1119 which then triggers the `SyncStore.peer_changed` event which then leads to `new_peers_with_peak` being  overwritten here https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1093

2023-03-22 18:19 UTC, almogdepaz commented
> Hm, looking at the surrounding code this removal and the usage of `peers_with_peak ` seems strange to begin with. We remove from `peers_with_peak` which is created outside the task and not longer used anywhere else because we copy it into `new_peers_with_peak` in the task
> 
> https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1070
> 
> 
> Yes its "used" in the validation task to remove peers but this doesn't really make sense imo. I think we can also just drop those two lines?
> https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1117-L1118
> 
> 
> It seems its enough to just close the connection there, what we already do
> https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1119
> 
> which then triggers the `SyncStore.peer_changed` event which then leads to `new_peers_with_peak` being overwritten here
> https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1093

i think i agree with you, when i wrote it originally we dident use this new_peers_with_peak it looks like Mariano added at at some point but im not sure i understand why

2023-04-20 02:59 UTC, altendky commented
My goal here was to quiet down the logs so when monitoring for errors we can see errors.  This is certainly just one step, but it's a step.  Does this make things significantly worse?  Would you like to provide another refactor that avoids the irrelevant `ERROR` log entry?

2023-05-01 08:03 UTC, almogdepaz commented
> My goal here was to quiet down the logs so when monitoring for errors we can see errors. This is certainly just one step, but it's a step. Does this make things significantly worse? Would you like to provide another refactor that avoids the irrelevant `ERROR` log entry?

actually  we use the copy of the list so we dont remove from the same list while we are iterating on it, i would just merge as is

2023-05-01 08:05 UTC, almogdepaz commented
> > Hm, looking at the surrounding code this removal and the usage of `peers_with_peak ` seems strange to begin with. We remove from `peers_with_peak` which is created outside the task and not longer used anywhere else because we copy it into `new_peers_with_peak` in the task
> > https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1070
> > 
> > Yes its "used" in the validation task to remove peers but this doesn't really make sense imo. I think we can also just drop those two lines?
> > https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1117-L1118
> > 
> > It seems its enough to just close the connection there, what we already do
> > https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1119
> > 
> > which then triggers the `SyncStore.peer_changed` event which then leads to `new_peers_with_peak` being overwritten here
> > https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1093
> 
> i think i agree with you, when i wrote it originally we dident use this new_peers_with_peak it looks like Mariano added at at some point but im not sure i understand why, was changed here #13320

@xdustinface actually we use the copy of the list so we dont remove from the same list while we are iterating on it, i would just merge as is

2023-05-01 08:06 UTC, almogdepaz approved these changes

2023-05-01 08:29 UTC, xdustinface commented
> @xdustinface actually we use the copy of the list so we dont remove from the same list while we are iterating on it, in python that would shift items to the left while we are still working on the list, i would just merge as is

I don't see where we would remove while iterating. We iterate over `random.sample(new_peers_with_peak)` which returns a new list. Also, like i pointed out initially, `new_peers_with_peak` gets anyway overwritten every time `SyncStore.peers_changed` gets triggered so removal from `peers_with_peak` doesn't make sense at all. See https://github.com/Chia-Network/chia-blockchain/blob/aafe234cd29c0c4aeef7b53a8a0875477cc918a6/chia/full_node/full_node.py#L1093

I just opened #15165 as alternative to this PR.

2023-05-04 20:15 UTC, closed without merging