Give a type to  tuple representing peak (height and block hash) of peer
Chia-Network/chia-blockchain pull request #14853
Opened 2023-03-20 14:57 UTC by aqk

### Purpose:

Code cleanup
Give a type to  tuple representing peak (height and block hash) of peer

No Behavior Changes

2023-03-20 15:05 UTC, altendky requested changes
Pending CI and the light tweak, I like it.  Thanks.

2023-03-20 15:05 UTC, altendky commented on chia/wallet/wallet_node.py
> +@dataclasses.dataclass
I'd default to this at least when there are immutable attribute types and we don't need to mutate.

```suggestion
@dataclasses.dataclass(frozen=True)
```

2023-03-21 04:11 UTC, altendky submitted a review, later dismissed

2023-05-23 21:22 UTC, altendky approved these changes

2023-05-23 23:41 UTC, emlowe approved these changes

2023-05-24 00:53 UTC, merged