Correct SQLite logging when using db_wrapper.manage_connection()
Chia-Network/chia-blockchain pull request #14866
Opened 2023-03-21 12:15 UTC by altendky

### Purpose:

Previously the log file was closed prior to even yielding the connection so none of the actual use of the connection would be expected to write to the file.

### Current Behavior:

### New Behavior:

### Testing Notes:

2023-03-21 12:17 UTC, arvidn approved these changes, later dismissed

2023-03-21 14:48 UTC, arvidn submitted a review, later dismissed

2023-03-22 06:35 UTC, wallentx requested changes, later dismissed
Mypy failing 😭

2023-03-22 15:09 UTC, arvidn approved these changes

2023-03-23 00:52 UTC, altendky commented
> Mypy failing sob

Could you dismiss the requested change?

2023-04-03 18:33 UTC, merged