add explicit listen option for Service() and ChiaServer.start_server()
Chia-Network/chia-blockchain pull request #14932
Opened 2023-03-29 01:22 UTC by altendky

### Purpose:

### Current Behavior:

### New Behavior:

### Testing Notes:

2023-03-29 03:54 UTC, xdustinface requested changes
Calling `ChiaServer.start_server` although we don't want to run a server seems strange to begin with, no? Wouldn't it make more sense to not call `ChiaServer.start_server` at all if we don't want to start a listening server instead of returning earlier based on a `listen` parameter? I guess we could just create the garbage collection task (which is the only thing left in there for non listening services) in maybe `ChiaServer.start_client` also or just in `ChiaServer.create`.

2023-03-29 13:26 UTC, altendky commented
This was indeed a tightly focused PR intended just to get the hard coded list of non-listening node types converted to parameters.  I agree with the oddity around the method name and the behavior, both existing and new.  Moving the garbage collection task creation to the `.create()` method would require making it async.  It is presently called from `Service.__init__()` which is called from `create_*_service()` which are also sync so that would be another bulk change.  Though, those are all called from their corresponding `async_main()` functions so not entirely implausible.

2023-03-30 03:52 UTC, xdustinface approved these changes

2023-04-11 15:27 UTC, emlowe approved these changes

2023-04-11 20:24 UTC, merged