Additional logging for datalayer wrt plugins
Chia-Network/chia-blockchain pull request #15032
Opened 2023-04-12 23:20 UTC by emlowe

Some additional logging around using uploader/downloader plugins in Datalayer

2023-04-15 11:42 UTC, altendky requested changes, later dismissed

2023-04-15 11:42 UTC, altendky commented on chia/data_layer/data_layer.py
> +                                        "generation {publish_generation}"
I think this was meant.

```suggestion
                                        f"Uploaded files to {uploader} for store {tree_id.hex()} "
                                        f"generation {publish_generation}"
```

2023-04-16 09:13 UTC, almogdepaz commented on chia/data_layer/data_layer.py
> +                                else:
i dont think you need the else here as we will break if we go into the if clause

2023-04-17 14:24 UTC, emlowe commented
Closing PR as code changes were included elsewhere

2023-04-17 14:24 UTC, closed without merging