wallet: Move `WalletPeers` init to the end of `_start_with_fingerprint`
Chia-Network/chia-blockchain pull request #15150
Opened 2023-04-28 06:32 UTC by xdustinface

### Purpose:

Moves the init of `WalletPeers` to the end of the start method to make sure we only connect to peers after we initialised and set up everything properly. This should like #15149 and #15148 also fix #15142 because we should not come into the situation where we modify `WalletStateManager.wallets` without connecting to peers, but yeah, i think it makes sense take them all into the release :)

### Current Behavior:

The wallet starts to connect to peers before everything is setup properly in `WalletStateManager`.

### New Behavior:

The wallet starts to connect to peers when everything is setup and initialised.

2023-05-01 19:50 UTC, wallentx commented
Targeting this to main, as per discussed in LR

2023-05-09 18:08 UTC, emlowe requested changes
Looks like some things got a little mixed in 
-gui change
block_header_validation
etc,

2023-05-10 02:58 UTC, xdustinface commented
> Looks like some things got a little mixed in during the base branch switch

Oh yeah, rebased on `main`!

2023-05-11 15:29 UTC, emlowe approved these changes

2023-05-12 00:04 UTC, merged