refactor WebSocketServer.ping_task() to loop
Chia-Network/chia-blockchain pull request #15408
Opened 2023-05-31 12:28 UTC by altendky

### Purpose:

### Current Behavior:

### New Behavior:

### Testing Notes:

2023-05-31 16:12 UTC, wjblanke requested changes

2023-07-05 19:48 UTC, altendky commented on chia/daemon/server.py
> +                        for connection in connections:
I think this was addressed in the catch up merge.

2023-07-17 16:25 UTC, wjblanke approved these changes, later dismissed
aok

2023-10-27 16:43 UTC, wjblanke approved these changes
aok

2023-10-27 19:03 UTC, merged