Add a path in wallets_prefarm test fixture for generating an RPC client
Chia-Network/chia-blockchain pull request #15426
Opened 2023-06-01 14:49 UTC by Quexington

Previously, it was impossible to use the `wallets_prefarm` test fixture and get the information you needed to spin up a `WalletRpcClient` to use in a test.  This PR modifies the fixture to add all of the arguments you would need to do so to a private variable on the wallet node `._test_client_args`.  This way, you can now go `WalletRpcClient.create(*wallet_node._test_client_args)` to get an RPC client in a test that uses this fixture.

2023-06-02 16:15 UTC, xdustinface requested changes

2023-06-05 16:20 UTC, Quexington commented on tests/conftest.py
> +    wallet_node_0._test_client_args = (
I took your suggestion to separate it out into a separate fixture

2023-06-06 12:03 UTC, xdustinface commented on tests/conftest.py
> +    wallet_node_0._test_client_args = (
Thanks, left two comments about it.

2023-06-06 15:13 UTC, Quexington commented on tests/conftest.py
> +async def wallets_prefarm_services(two_wallet_nodes_services, self_hostname, trusted):
Okay I changed it to return the services

2023-06-06 15:23 UTC, xdustinface approved these changes

2023-06-06 16:57 UTC, trepca approved these changes

2023-06-06 17:40 UTC, merged