Test announcement condition limits for v2.0 soft-fork
Chia-Network/chia-blockchain pull request #15576
Opened 2023-06-21 18:53 UTC by aqk

### Purpose:

Adds a test

### Current Behavior:

### New Behavior:

Adds a test for behaviour introduced in rules to be introduced in a future release.
Tests soft-forked condition limit.

### Testing Notes:

2023-06-21 18:54 UTC, aqk commented
Arvid, let me know the best way to import the new behaviour to exercise the `softfork2=True` branches of the test.

2023-06-21 22:06 UTC, arvidn requested changes

2023-06-21 22:06 UTC, arvidn commented on tests/core/full_node/test_conditions.py
> +        await check_conditions(bt, conditions_program, expected_err=expected_err, softfork2=softfork2)
I think you want to always just pass `False` as `softfork2.

2023-07-17 01:45 UTC, arvidn commented
I made an updated PR of this here: https://github.com/Chia-Network/chia-blockchain/pull/15790

2026-07-27 20:17 UTC, closed without merging