Fix Flaky Simulator CLI Tests
Chia-Network/chia-blockchain pull request #15618
Opened 2023-06-25 20:37 UTC by jack60612

### Purpose:
This PR makes the simulator cli tests less flaky 

### Current Behavior:

### New Behavior:

### Testing Notes:

2023-06-30 03:49 UTC, jack60612 commented
slow runners tend to be windows, so this solves the issue of block creation timing out on those runners.

2023-07-05 13:04 UTC, altendky reviewed
The `try`/`except` looks more like an `if`.

I haven't thought about which is better, but you can also have exceptions propagated by `.invoke()` instead of checking exit codes.  At least I think that ends up fairly similarly, but more informative, given how you control exit codes with click.

This feels like polling for completion where I would expect the pattern to be more like `while` and `if`/`break` or such.  Or perhaps the `revert` subcommand should grow a `--wait` or option or such?

Seemingly, we need a more machine parsable output from the `status` subcommand as well.

2023-07-25 22:33 UTC, arvidn commented on tests/cmds/test_sim.py
> +        assert "Height:          8" in reorg_fallback.output
there's no coverage for this in the tests, which would seem fine given that this is an `AssertionError`. But we actually *swallow* this error and don't necessarily fail the test, which looks super shady. How can you know the assertion isn't a serious failure that is caused by a bug? In fact, aren't all assertion failures caused by bugs?

2023-10-10 17:48 UTC, emlowe requested changes
I think my fix here is a better fix. Adjust the RPC timeout to be longer so this completes in CI:
https://github.com/Chia-Network/chia-blockchain/pull/16545

2024-01-03 22:59 UTC, closed without merging