Fix DID resync
Chia-Network/chia-blockchain pull request #15675
Opened 2023-07-01 16:52 UTC by ytx1991

### Purpose:
During the resync, it may create DID wallets that don't belong to the current key. These wallets will not be removed after fully synced. It confuses users.

### Current Behavior:

### New Behavior:
Only create DID wallet when we see the DID coin the first time, and it is unspent.

### Testing Notes:

2023-07-06 10:42 UTC, xdustinface requested changes
There is a `print` which should be dropped. And do you understand why this even happens during a sync because actually the coin states should be sorted so that unspent coin states come before spent ones? I know there are cases where we due to batching/task processing of the coin states might still process them out of order but here this should probably not be this case.. ? After quick check this feels like this might become flaky because you not really force the coin states to be out of order in the added test.

2023-07-06 10:42 UTC, xdustinface commented on chia/wallet/wallet_state_manager.py
> +                print("test")
```suggestion
```

2023-07-06 17:16 UTC, ytx1991 commented
I have added a check while fixing Clawback resync. It will log something if the coin state in add_coin_states is unspent but in the latest block the coin state is spent. I resynced several times but never see that log printed so I assume during the resync, the wallet will not receive an unspent coin state for a spent coin. I thought there should be two coin states for a spent coin, but seems like it only has one coin state.

2023-07-21 05:51 UTC, xdustinface requested changes
> so I assume during the resync, the wallet will not receive an unspent coin state for a spent coin.

Okay yeah thats right. I digged more into this and its indeed because we alter the states in the full node and of course then only send the spent states after.

I think it would be good to add the the proposed renaming for the test, it makes it easier to read/understand it. 

Thinking about this test maybe you should just resync both wallets and also assert at the end that the DID wallets (not) exists for the particular wallet instead of only checking the tx record and unspent coin count? I also think, now you only test the resync after the coin was spent but not if the coin is still unspent. Do you think we should test all cases?

2023-07-26 10:05 UTC, xdustinface requested changes

2023-07-26 10:05 UTC, xdustinface commented on tests/wallet/did_wallet/test_did.py
> +        wallet_node_2.config = new_config_2
```suggestion
        wallet_node_1.config["reset_sync_for_fingerprint"] = fingerprint_1
        wallet_node_1.config["database_path"] = "wallet/db/blockchain_wallet_v2_test_1_CHALLENGE_KEY.sqlite"
        wallet_node_2.config["reset_sync_for_fingerprint"] = fingerprint_2
        wallet_node_2.config["database_path"] = "wallet/db/blockchain_wallet_v2_test_2_CHALLENGE_KEY.sqlite"
```

Why this copying?

2023-09-04 05:54 UTC, xdustinface approved these changes

2023-10-05 17:48 UTC, wjblanke approved these changes, later dismissed
aok

2023-10-05 21:10 UTC, wjblanke approved these changes
aok thanks kyle

2023-10-05 22:37 UTC, merged