Delete DL files on unsubscribe.
Chia-Network/chia-blockchain pull request #16182
Opened 2023-08-28 16:49 UTC by fchirica

Removes both locally stored full files and delta files when we unsubscribe to a delta layer store.

2023-08-29 14:51 UTC, altendky requested changes

2023-08-29 14:51 UTC, altendky commented on chia/data_layer/data_layer.py
> +                os.remove(file_path)
```suggestion
            try:
                file_path.unlink()
            except FileNotFoundError:
                pass
```

2023-08-29 14:51 UTC, altendky commented on tests/core/data_layer/test_data_rpc.py
> +        for batch_count in range(10):
I think a variable for the `10` would be helpful.  Then the `20` below could reference it for clarity.

```suggestion
        update_count = 10
        for batch_count in range(update_count):
```

2023-08-29 14:51 UTC, altendky commented on tests/core/data_layer/test_data_rpc.py
> +            assert len(filenames) == 20
May as well dedent as well.

```suggestion
            assert len(filenames) == 2 * update_count
```

2023-08-29 14:51 UTC, altendky commented on tests/core/data_layer/test_data_rpc.py
> +            filenames = {entry.name for entry in entries}
Feels like 
```suggestion
        filenames = {path.name for path in data_layer.server_files_location.iterdir()}
```

2023-08-29 14:51 UTC, altendky commented on tests/core/data_layer/test_data_rpc.py
> +            await asyncio.sleep(10)
This should probably be based on two times the read out configuration variable.  Or, preferably have a mechanism for waiting for the next periodic data management cycle.  But I'm ok leaving that for "later".  Would be nice though.

2023-08-29 14:51 UTC, altendky commented on tests/core/data_layer/test_data_rpc.py
> +            assert len(filenames) == 0
As above.

2023-08-29 18:57 UTC, altendky submitted a review, later dismissed
thanks

2023-08-30 01:04 UTC, altendky approved these changes, later dismissed

2023-08-30 15:11 UTC, emlowe submitted a review, later dismissed
Approved - well add separate issue to create a `retain` option

2023-09-06 22:48 UTC, emlowe approved these changes

2023-09-06 23:26 UTC, emlowe commented
Coverage diff exception approved

2023-09-06 23:48 UTC, merged