Avoid setting test config items to their default values
Chia-Network/chia-blockchain pull request #16225
Opened 2023-09-01 21:56 UTC by AmineKhaldi

2023-09-10 10:44 UTC, arvidn approved these changes, later dismissed

2023-09-10 13:46 UTC, altendky requested changes
If we want this, shouldn't we have the matrix generation enforce it?

2023-09-12 17:32 UTC, altendky approved these changes

2023-09-18 10:37 UTC, arvidn approved these changes

2023-09-19 13:36 UTC, merged