Add RPC Client context manager
Chia-Network/chia-blockchain pull request #16289
Opened 2023-09-08 20:27 UTC by Quexington

This gives an easy way to get an RPC client in a context manager so you can't forget to close it.

2023-09-19 17:22 UTC, altendky approved these changes

2023-09-19 17:30 UTC, Quexington commented on chia/rpc/rpc_client.py
> +    async def create_as_context(cls: Type[_T_RpcClient], *args) -> AsyncIterator[RpcClient]:
Changed

2023-09-20 22:54 UTC, altendky requested changes

2023-09-20 22:54 UTC, altendky commented on chia/rpc/rpc_client.py
> +            net_config,
```suggestion
            self_hostname=self_hostname,
            port=port,
            root_path=root_path,
            net_config=net_config,
```

2023-09-21 13:41 UTC, altendky approved these changes

2023-09-21 17:58 UTC, wjblanke approved these changes
aok

2023-09-21 20:03 UTC, merged