Add a few missing type annotations
Chia-Network/chia-blockchain pull request #17043
Opened 2023-12-12 18:00 UTC by Rigidity

### Purpose:

Adds type annotations that were missing in a few places, which mypy (configured more strictly for my editor, presumably) was complaining about.

### Current Behavior:

### New Behavior:

### Testing Notes:

2023-12-12 19:18 UTC, AmineKhaldi approved these changes, later dismissed

2023-12-19 20:28 UTC, altendky requested changes
I would guess your IDE isn't using mypy.  If it were and was using the strict config or such it'd be complaining a lot more.  But, I'm just guessing.

2023-12-19 20:28 UTC, altendky commented on chia/util/struct_stream.py
> +    __bytes__: None = None
This was changed in release and then checkpointed so presumably it is just conflicted.  It's a regular function def again (for now) so probably just revert this.

```suggestion
    __bytes__ = None
```

2023-12-19 20:29 UTC, altendky commented on chia/util/keyring_wrapper.py
>      __keys_root_path: Path = DEFAULT_KEYS_ROOT_PATH
```suggestion
    __shared_instance: ClassVar[Optional[KeyringWrapper]] = None
    __keys_root_path: ClassVar[Path] = DEFAULT_KEYS_ROOT_PATH
```

2023-12-19 20:30 UTC, Rigidity commented
> I would guess your IDE isn't using mypy. If it were and was using the strict config or such it'd be complaining a lot more. But, I'm just guessing.

It should be, don't know why it didn't catch this. Do I need to configure it to lint more strictly?

2023-12-20 01:28 UTC, altendky submitted a review, later dismissed

2024-01-02 18:33 UTC, altendky approved these changes

2024-01-08 14:12 UTC, arvidn approved these changes

2024-01-08 14:36 UTC, merged