Fix compressed blocks
Chia-Network/chia-blockchain pull request #17071
Opened 2023-12-16 12:56 UTC by arvidn

### Purpose:

`BlockTools` require the ability to generate invalid blocks, for negative tests. Originally, `BlockTools` used the production versions of `create_unfinished_block()` and `create_foliage()`. However, these functions are made to only generate valid blocks, so it was duplicated and modified in the `block_tools.py` file, to avoid mixing test code with production code. However, `BlockTools` was the only reason the production code had test coverage, so this change (a long time ago) removed test coverage for the production code generating blocks.

This PR restores `BlockTools` to use the production versions of `create_unfinished_block()` and `create_foliage()`. In order to still be able to customize these functions to accept invalid blocks, two customization points are introduced. `compute_cost`  and `compute_fees`.

1. `compute_cost()` uses the real block validation code in production, which won't allow invalid blocks. The test version attempts to compute the cost with as little validation as possible
2. `compute_fees()` does not allow negative fees in production (it's stored in an unsigned field) whereas the test version clamps negative fees to 0, thus allowing tests to create blocks that mint coins.

### Current Behavior:

`create_unfinished_block()` and `create_foliage()` do not have test coverage.

### New Behavior:

`create_unfinished_block()` and `create_foliage()` *do* have test coverage.

2023-12-17 19:05 UTC, altendky requested changes

2023-12-17 19:05 UTC, altendky commented on tests/core/consensus/test_block_creation.py
> +    agg_sig_cost = 1200000 * num_coins
Where do these literals come from?

2023-12-17 19:05 UTC, altendky commented on tests/core/consensus/test_block_creation.py
> +    print(cost)
Maybe more than this would be good, but at least have some sort of text with the output.

```suggestion
    print(f"{cost=}")
```

2023-12-17 19:05 UTC, altendky commented on tests/core/consensus/test_block_creation.py
> +        expected = 50316699
I guess this will make sure it doesn't change, not clear about the literals again here though and what makes them correct.

2023-12-17 23:20 UTC, arvidn commented on tests/core/consensus/test_block_creation.py
> +    agg_sig_cost = 1200000 * num_coins
fixed

2023-12-18 12:11 UTC, altendky approved these changes

2023-12-18 16:47 UTC, emlowe approved these changes

2023-12-18 16:48 UTC, merged