Endpoint for vault singleton creation
Chia-Network/chia-blockchain pull request #17093
Opened 2023-12-19 17:40 UTC by geoffwalmsley

2024-01-02 22:41 UTC, Quexington approved these changes, later dismissed

2024-01-03 20:45 UTC, Quexington requested changes

2024-01-03 20:45 UTC, Quexington commented on chia/rpc/wallet_rpc_api.py
> +        entropy = bytes.fromhex(str(request.get("entropy")))
Can we call this "hidden_puzzle_hash" now?

2024-01-03 20:45 UTC, Quexington commented on chia/rpc/wallet_rpc_api.py
> +    @tx_endpoint(push=True)
Let's start making these False by default, the ones with push=True currently are just for backwards compatbility

2024-01-03 20:45 UTC, Quexington commented on chia/rpc/wallet_rpc_api.py
> +        )
I'd like to keep the RPCs as pass-thru as possible so maybe this should all go into WSM

2024-01-03 20:45 UTC, Quexington commented on chia/rpc/wallet_rpc_api.py
> +        announcement_message = Program.to([vault_puzzlehash, amount, bytes(0x80)]).get_tree_hash()
We should hint the secp_pk and hidden_puzzle_hash here so the information is not entirely lost to the chain

2024-01-03 20:45 UTC, Quexington commented on chia/rpc/wallet_rpc_api.py
> +        entropy = bytes.fromhex(str(request.get("entropy")))
Actually, on further thought, let's take this out and come up with something canonical to use for the entropy of the hidden puzzle hash:
```
def calculate_hp_w_index_for_vault(index, hidden_puzzle = DEFAULT_HIDDEN_PUZZLE):
  return Program.to([6, (index, hidden_puzzle)])
```

2024-01-03 20:45 UTC, Quexington commented on chia/rpc/wallet_rpc_api.py
> +        entropy = bytes.fromhex(str(request.get("entropy")))
I think we may need to have some way to make the entropy secret but we can add that later.

2024-01-03 20:45 UTC, Quexington commented on chia/rpc/wallet_rpc_api.py
> +        genesis_launcher_solution = Program.to([vault_puzzlehash, amount, bytes(0x80)])
Use the calculation you already did above

2024-01-03 20:45 UTC, Quexington commented on chia/rpc/wallet_rpc_api.py
> +            to_puzzle_hash=vault_full_puzzlehash,
Use the inner puzzle hash you sent to here

2024-01-03 20:45 UTC, Quexington commented on tests/wallet/vault/test_vault_wallet.py
> +    assert eve_coin
Can we push the transaction and add a `.process_pending_states` call here to make sure the transaction goes through properly?

2024-01-04 15:08 UTC, Quexington commented on chia/wallet/wallet_state_manager.py
> +            memos=[secp_pk, hidden_puzzle_hash],
One last nitpick, but these should go in the `genesis_launcher_solution` (where you currently have `None`) that way we don't have to fetch and run the spend before the launcher as well.

2024-01-05 22:52 UTC, Quexington approved these changes

2024-01-08 17:44 UTC, wjblanke approved these changes
aok

2024-01-08 17:58 UTC, merged