Mempool logging
Chia-Network/chia-blockchain pull request #17161
Opened 2023-12-24 23:24 UTC by arvidn

### Purpose:

Improve transparency of what full nodes are doing and where they spend their time.

1. Specify the post-processing time in the block validation timing warning. This is where the mempool is updated and can dominate the cost of adding a new block.
2. Specify queue depth in timing warning when validating a new transaction, slated for the mempool. This is to help identify which transaction took time, and which transactions just got stuck in the queue, behind it.
3. name worker processes to include which service they are part of (e.g. weight_proof, mempool, block_validation)
4. use monotonic clock when measuring time durations, rather than civic time

### Current Behavior:

In the logs, it's hard to tell the difference between a block that's expensive to validate vs. a block that causes the mempool to be expensive to update.

### New Behavior:

The logs clearly distinguishes between an expensive block validation vs. an expensive mempool update.

### Testing Notes:

example logs:

adding blocks:
```
2023-12-24T22:15:01.299 full_node chia.full_node.full_node: WARNING  Block validation time: 15.97 seconds, pre_validation time: 0.38 seconds, post-process time: 15.14 seconds, cost: 3969110680, percent full: 36.083% header_hash: a2603c310a4f3a57ca7540563e9fa8e54812e5d9061eb35da6b55bec17a2a614 height: 4703882
2023-12-24T23:04:55.825 full_node chia.full_node.full_node: WARNING  Block validation time: 2.67 seconds, pre_validation time: 0.77 seconds, post-process time: 0.79 seconds, cost: 5197174300, percent full: 47.247% header_hash: 552bc4c9846806c6ed0b230bdd843df5e6cbe51fa3d7709fe07bf147dd641b17 height: 4704033
```

adding transactions:
```
2023-12-24T21:41:13.317 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.0004 seconds for ba6876756847aba3fdb5f8b93110e645234388c788526f359924ccc06d73d55b (queue-size: 51)
2023-12-24T21:41:13.317 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.0008 seconds for 303ebdd9ce432a8e39646a5b9b8b179c4ce732a32db6145a8f72fa70362a64e7 (queue-size: 50)
2023-12-24T21:41:13.317 full_node chia.full_node.mempool_manager: WARNING  pre_validate_spendbundle took 2.0010 seconds for e80f758e8f01a2214ed2f21f5213a02f12a990fbe60a2e087283a0f086e331de (queue-size: 49)
```

processes:
```
$ ps ax | grep chia_full_node
 432814 pts/35   Rl   638:14 chia_full_node
 432940 pts/35   S      1:55 chia_full_node_block_validation_worker
 432941 pts/35   S      1:54 chia_full_node_block_validation_worker
...
 432975 pts/35   S     57:59 chia_full_node_mempool_worker
 432976 pts/35   S     57:48 chia_full_node_mempool_worker
```

2024-01-02 18:44 UTC, altendky requested changes

2024-01-02 18:44 UTC, altendky commented on chia/full_node/mempool_manager.py
> +        self._worker_queue_size -= 1
What about exceptions?

2024-01-03 13:25 UTC, altendky approved these changes

2024-01-03 16:48 UTC, emlowe approved these changes

2024-01-03 17:27 UTC, merged