Annotate wallet's block_record.py
Chia-Network/chia-blockchain pull request #17318
Opened 2024-01-12 19:04 UTC by AmineKhaldi

2024-01-12 20:59 UTC, emlowe approved these changes

2024-01-12 22:52 UTC, altendky requested changes
was reviewing the coverage and i think we may not use this.  looking.

2024-01-12 22:55 UTC, altendky commented
trying removal in https://github.com/Chia-Network/chia-blockchain/pull/17325

2024-01-16 13:12 UTC, AmineKhaldi commented
Superseded by PR #17325.

2024-01-16 13:12 UTC, closed without merging