DL multiple batch updates.
Chia-Network/chia-blockchain pull request #17414
Opened 2024-01-29 15:46 UTC by fchirica

### Purpose:

### Current Behavior:

### New Behavior:

### Testing Notes:

2024-02-03 00:09 UTC, emlowe commented on chia/cmds/data.py
> +@click.option("-p", "--publish_on_chain", help="Publish the result on chain", type=bool, default=True)
I would suggest not using a short option and using "--publish/--no-publish" as a flag

2024-02-09 22:24 UTC, emlowe commented
Now that this is all using `publish`, I'm wondering if `submit` isn't more consistent terminology with other parts of chia - for example, `Transaction submitted to nodes`

2024-02-12 15:36 UTC, altendky requested changes
My main concern is around the terminology and effects that may have.  The definitions at https://en.wiktionary.org/wiki/pending#Adjective are certainly inclusive of both our existing and new usage, but I feel like we are sort of changing from 3. (impending on-chain confirmation) to more of a 1./2. usage (incomplete, possibly needing more action taken to complete).  I think there is a concrete bug around this where clearing pending roots does clear one local batch update but not the previous ones as they are marked committed, if I am reading correctly.

2024-02-12 15:36 UTC, altendky commented on chia/data_layer/data_store.py
> +                AND status IN (:pending_status, :pending_batch_status) LIMIT 2
I'm a bit iffy about combining 'waiting for burying on chain' and 'in the middle of dealing with practical limits of inserting' as both being 'pending', particularly given the historical usage here.

2024-02-12 15:36 UTC, altendky commented on chia/data_layer/data_store.py
> +                    await self.change_root_status(pending_root, Status.COMMITTED)
This feels misleading as it is not committed on chain, it is merely not the latest pending (uncommited local, whatever term) root.  I don't know what all functional ramifications there are around this presently, but it seems like clearling 'pending' roots wouldn't work correctly with this.  Well, you wouldn't clear back to the latest on-chain root.

2024-02-12 15:36 UTC, altendky commented on chia/rpc/data_layer_rpc_api.py
> +            return {}
Should we just always contain the `tx_id` key?  I don't know what we tend to do in our RPCs regarding this question.  There are at least a couple more cases below.

2024-02-12 15:36 UTC, altendky commented on tests/core/data_layer/test_data_rpc.py
> +                await full_node_api.farm_new_transaction_block(FarmNewBlockProtocol(ph))
Similar below.

```suggestion
            await full_node_api.farm_blocks_to_puzzlehash(count=NUM_BLOCKS_WITHOUT_PUBLISH, guarantee_transaction_blocks=True)
```

2024-02-12 15:36 UTC, altendky commented on tests/core/data_layer/test_data_rpc.py
> +        assert pending_root is None
Also check the latest confirmed root.  I believe there is a bug here where it will be the second to last unpublished batch.

2024-02-12 15:36 UTC, altendky commented on tests/core/data_layer/test_data_store.py
> +    await data_store.change_root_status(root, Status.PENDING_BATCH)
I think it would be nice to have a separate test (or two more?) for granular results.

2024-02-15 15:57 UTC, altendky commented
I misunderstood and thought the pending batch -> committed status was a permanent thing rather than an intermediate change that would get reverted.  My above review has several comments that I think end up related to this so I will go back through and review them now.

2024-02-15 18:42 UTC, altendky submitted a review, later dismissed

2024-02-22 16:37 UTC, fchirica commented
Removing coverage diff: only exceptions thrown in case of bugs are failing now

2024-02-22 16:45 UTC, altendky approved these changes

2024-02-23 16:34 UTC, emlowe approved these changes

2024-02-23 17:56 UTC, merged