Update black to 24.1.1 and update source as needed
Chia-Network/chia-blockchain pull request #17499
Opened 2024-02-06 16:49 UTC by emlowe

Update black to 24.1.1
Update source by running black 24.1.1
Update flake8 config for some extra ignores per black docs

2024-02-06 16:54 UTC, Quexington approved these changes, later dismissed
Not enthused about the merge conflicts incoming but yeah I mean looks good :+1:

2024-02-07 15:55 UTC, altendky requested changes
Just being super explicit that this shouldn't go in while we have a release branch.

2024-03-12 15:39 UTC, altendky submitted a review, later dismissed

2024-03-12 15:43 UTC, altendky approved these changes

2024-03-13 17:10 UTC, arvidn approved these changes

2024-03-13 18:08 UTC, merged