Added `--skip-keyring` option to `chia start xxx` command
Chia-Network/chia-blockchain pull request #17857
Opened 2024-04-11 13:58 UTC by ChiaMineJP

This PR fixes https://github.com/Chia-Network/chia-blockchain/issues/17848

When GUI starts up, it calls `chia start daemon`.
In some circumstance, the process of `chia start daemon` wait for user input and never exit.
(The circumstance: Enabled passphrase protection. Not storing passphrase to OS's credential store)

This PR adds `-s/--skip-keyring` option to `chia start daemon` which won't wait for user input for passphrase in the above circumstance.

Todo:
- Update GUI to launch daemon by `chia start daemon --skip-keyring`

2024-04-11 14:15 UTC, arvidn commented on chia/cmds/start.py
> +def start_cmd(ctx: click.Context, restart: bool, skip_keyring: bool, group: tuple[str, ...]) -> None:
```suggestion
def start_cmd(ctx: click.Context, restart: bool, *, skip_keyring: bool, group: tuple[str, ...]) -> None:
```

would that work?

2024-04-11 14:15 UTC, arvidn commented on chia/cmds/start_funcs.py
> +    root_path: Path, config: Dict[str, Any], skip_keyring: bool
```suggestion
    root_path: Path, config: Dict[str, Any], *, skip_keyring: bool
```

I think this would be good too

2024-04-11 14:15 UTC, arvidn commented on chia/cmds/start_funcs.py
> +    root_path: Path, config: Dict[str, Any], group: tuple[str, ...], restart: bool, skip_keyring: bool
```suggestion
    root_path: Path, config: Dict[str, Any], group: tuple[str, ...], restart: bool, *, skip_keyring: bool
```
would this work?

2024-04-11 14:20 UTC, ChiaMineJP commented on chia/cmds/sim_funcs.py
> +    await async_start(root_path, config, ("simulator",), False, False)
I updated the code to use named parameters.

2024-04-11 14:21 UTC, ChiaMineJP commented on chia/cmds/start_funcs.py
> +    root_path: Path, config: Dict[str, Any], skip_keyring: bool
I adopted this suggestion.

2024-04-11 14:21 UTC, ChiaMineJP commented on chia/cmds/start_funcs.py
> +    root_path: Path, config: Dict[str, Any], group: tuple[str, ...], restart: bool, skip_keyring: bool
I adopted this suggestion.

2024-04-11 16:07 UTC, arvidn approved these changes, later dismissed

2024-04-12 15:49 UTC, emlowe commented
Close and reopen to see what's up with CI

2024-04-12 17:40 UTC, ChiaMineJP commented
@emlowe @arvidn 
I've fixed a test. It looked like that a daemon process launched by a previous test case remained and prevented a new daemon process to start in a next test case.

2024-04-12 21:27 UTC, emlowe commented
Most of the current failure in `cmds` are because the job is getting terminated after 30 mins - it's possible you have introduced some minor slowdown causing it to go over - or possible there is an actual hang somewhere. The default `job_timeout` is 30 mins.

I notice Ubuntu pass in some cases though.

You might consider increasing the job timeout to see if that works - you can set this in `_tests/cmds/config.py` and set `job_timeout = 45` or something. If that passes, we do have some tools we can use to find the best number to use

2024-04-13 02:40 UTC, ChiaMineJP commented
@emlowe 
Maybe launching daemon process in the test is the problem. The daemon process stalls somewhere. (Maybe waiting for user input)
I replaced the code to launch daemon with mock.

2024-04-13 11:46 UTC, ChiaMineJP commented
It seems like config file locking issue.
I investigated with this PR https://github.com/Chia-Network/chia-blockchain/pull/17866.
Test cases in `chia/_test/cmds` run parallel and some of those tests are trying to lock and load config which seem to cause config file dead locking.

I removed to use `bt: BlockTools` fixture and this seems resolving the issue.

2024-04-16 07:19 UTC, arvidn submitted a review, later dismissed

2024-04-16 11:05 UTC, arvidn submitted a review, later dismissed

2024-04-16 11:53 UTC, arvidn requested changes

2024-04-16 11:56 UTC, arvidn approved these changes, later dismissed

2024-04-16 18:41 UTC, arvidn commented
I suspect the missing coverage was not introduced by this PR

2024-04-17 13:39 UTC, arvidn approved these changes

2024-04-17 17:02 UTC, merged