Optimize DL autoinserts.
Chia-Network/chia-blockchain pull request #17883
Opened 2024-04-17 11:49 UTC by fchirica

### Purpose:

### Current Behavior:

### New Behavior:

### Testing Notes:

2024-04-25 14:11 UTC, fchirica commented
PR improves in CI from 1000 inserts in 36s to 25000 inserts in 52s. Locally on my laptop, I can do 100000 single batch inserts in 22s now.

2024-04-26 15:03 UTC, altendky requested changes

2024-04-26 15:03 UTC, altendky commented on chia/_tests/core/data_layer/test_data_store.py
> +)
Were we intending to provide more parametrizations?

2024-04-26 19:13 UTC, altendky commented on chia/data_layer/data_store.py
> +                return node
There seems to be some more complexity in our query along with the desire to not only have breadth first but also to terminate early after finding the first leaf node.  If we think we can still manage something better, we'll take it on in a separate PR.

2024-04-26 19:53 UTC, altendky submitted a review, later dismissed

2024-04-29 11:49 UTC, altendky approved these changes

2024-04-29 12:14 UTC, altendky requested changes
we are talking through back-compat

2024-05-07 13:28 UTC, altendky requested changes
suggested alternate form, feel free to close these conversations if you prefer to keep it as is

2024-05-07 14:25 UTC, altendky approved these changes, later dismissed

2024-05-08 18:37 UTC, emlowe approved these changes

2024-05-08 18:38 UTC, altendky approved these changes

2024-05-09 13:55 UTC, merged