Optimize min height leaf.
Chia-Network/chia-blockchain pull request #18123
Opened 2024-06-06 15:15 UTC by fchirica

### Purpose:

### Current Behavior:

### New Behavior:

### Testing Notes:

2024-06-07 19:34 UTC, altendky requested changes

2024-06-07 19:34 UTC, altendky commented on chia/data_layer/data_store.py
> +                raise Exception(f"Node not found for hash: {node_hash.hex()}")
Could do a set difference as well to get the list of missing stuff i think.  Or at least collect them all to report in the error.

2024-06-10 14:02 UTC, altendky approved these changes

2024-06-25 20:44 UTC, emlowe approved these changes

2024-06-26 16:22 UTC, merged