Stop auto-subscribing to local stores
Chia-Network/chia-blockchain pull request #18166
Opened 2024-06-12 17:53 UTC by emlowe

Stop auto-subscribing to local stores found in the DB that aren't already subscribed

Some experimentation in this Draft to see how this works.

Can be turned back to the original behaviour by putting `auto_subscribe_to_local_stores` to True in `config.yaml`

2024-07-24 19:47 UTC, emlowe commented
close and reopen for new CI run

2024-07-24 20:30 UTC, altendky requested changes

2024-07-24 20:30 UTC, altendky commented on chia/data_layer/data_layer.py
> +                        # subscription = await self.subscribe(store_id, [])
?

```suggestion
```

2024-07-31 16:37 UTC, emlowe commented
close and reopen for CI

2024-08-07 01:07 UTC, altendky approved these changes

2024-08-07 18:49 UTC, arvidn approved these changes

2024-08-07 18:54 UTC, merged