make Program.run() and Program.run_with_cost() default to enabling all the most recent features
Chia-Network/chia-blockchain pull request #18370
Opened 2024-07-29 22:54 UTC by arvidn

and to disallow unknown opcodes (i.e. strict mode). To have full control of which features are enabled, introduce a run2() function

### Purpose:

### Current Behavior:

### New Behavior:

### Testing Notes:

2024-07-30 19:20 UTC, richardkiss commented on chia/types/blockchain_format/program.py
>      def run(self, args: Any) -> Program:
I did a bad job in evolving this `run` function. In hindsight, I think we should consider this:

```suggestion
    def run(self, args: Any, /, max_cost=INFINITE_COST, flags=DEFAULT_FLAGS) -> Program:
```

Then we can move `DEFAULT_FLAGS` to the top level and just define `run_with_cost` in terms of `run` (and maybe even deprecate it).

2024-07-30 19:21 UTC, richardkiss commented on chia/types/blockchain_format/program.py
>      def run(self, args: Any) -> Program:
Maybe we don't even need the `._run` method anymore.

2024-07-31 07:10 UTC, richardkiss requested changes
See comments

2024-08-01 18:17 UTC, richardkiss submitted a review, later dismissed

2024-08-07 20:28 UTC, richardkiss approved these changes

2024-08-07 20:32 UTC, emlowe approved these changes

2024-08-07 20:33 UTC, emlowe commented
There doesn't seem much difference now between `run` and `run_with_flags`

2024-08-07 22:01 UTC, richardkiss commented
> There doesn't seem much difference now between `run` and `run_with_flags`

Yeah, as I mentioned above maybe we consider deprecating it.

2024-08-07 22:04 UTC, Starttoaster commented
Waiting on merge for all conversations to resolve.

2024-08-08 06:21 UTC, arvidn commented
the difference is that `run()` only returns the result, not the cost. I think we should keep both for now, to not break any 3rd party using this class.

2024-08-08 07:58 UTC, merged