Rename `Spend` to `SpendConditions`
Chia-Network/chia-blockchain pull request #18438
Opened 2024-08-09 15:33 UTC by matt-o-how

### Purpose:

Includes a Try to catch if the new name doesn't exist yet and fall back to the old import.
This patch will need to land before the Rust equivalent due to a circular dependency in the Rust's pytests.

2024-08-12 08:12 UTC, arvidn requested changes

2024-08-12 08:12 UTC, arvidn commented on chia/types/spend_bundle_conditions.py
> +    SpendConditions = chia_rs.Spend
I would hold off on this and make this change when we bump `chia_rs` next

2024-08-12 08:12 UTC, arvidn commented on chia/types/spend_bundle_conditions.py
> +    SpendConditions = chia_rs.Spend
I'm referring to supporting both old and new `chia_rs`. I think it's fine to only support the version that we depend on right now.

2024-08-12 11:04 UTC, arvidn commented on chia/types/spend_bundle_conditions.py
> +    SpendConditions = chia_rs.Spend
the circular dependency between chia_rs and chia-blockchain makes this a bit tricky

2024-08-12 11:04 UTC, arvidn approved these changes, later dismissed

2024-08-12 16:20 UTC, Starttoaster commented
@matt-o-how @arvidn - This PR needs a determination on the coverage diff prior to merge

2024-08-14 15:35 UTC, arvidn approved these changes

2024-08-14 16:25 UTC, merged