add test targets just for pre-generating the test chains
Chia-Network/chia-blockchain pull request #18525
Opened 2024-08-26 08:39 UTC by arvidn

### Purpose:

Make it easier to work with our test chains (cached in the `test-cache` repo).
Specifically, when running tests in parallel (with `pytest-xdist`) these fixtures are instantiated in parallel, in different processes. This means we are likely to generate the chains multiple times concurrently. This adds dummy test targets with the sole purpose of triggering each fixture once. So you can still generate all test chains concurrently.

### Current Behavior:

running `pytest` with multiple processes on a clean install (not using the `test-cache` repo) will generate the test chains multiple times, redundantly.

### New Behavior:

The test chains can be generated as a separate step, before running the tests, by running:

```
pytest -m build_test_chains
```

2024-08-29 12:06 UTC, altendky requested changes

2024-08-29 12:06 UTC, altendky commented on tools/compare_chains.py
> +from recursive_diff import recursive_diff
Needs to be added as a dependency in the dev group.  I think?

2024-08-29 12:06 UTC, altendky commented on tools/compare_chains.py
> +    chain2 = load_chain(Path(sys.argv[2]))
I would just use click.  Feel free to close this comment instead of taking action.

2024-09-03 21:22 UTC, arvidn commented
I decided to just drop the comparison tool

2024-09-04 00:20 UTC, altendky approved these changes

2024-09-04 15:56 UTC, wjblanke approved these changes
aok

2024-09-04 21:53 UTC, merged