Added `offer_only` option to `create_offer_for_ids`
Chia-Network/chia-blockchain pull request #18680
Opened 2024-10-07 15:35 UTC by ChiaMineJP

There is a case where response payload size of `create_offer_for_ids` hits the limit of websocket connection.
I've added an `offer_only` flag for `create_offer_for_ids` which lets the API respond only `offer_data` and `trade_record` properties to reduce response payload size.

2026-03-31 18:53 UTC, BrandtH22 requested changes

2026-03-31 18:53 UTC, BrandtH22 commented on chia/rpc/wallet_rpc_api.py
> +                    "trade_record": trade_record.to_json_dict_convenience(),
This needs to not include the trade_record to resolve the payload issues. Just remove this line

2026-04-01 16:32 UTC, ChiaMineJP commented on chia/rpc/wallet_rpc_api.py
> +                    "trade_record": trade_record.to_json_dict_convenience(),
Could you see the latest change? I've merged commits from `main` and it drastically changes the file structure.

2026-06-05 14:37 UTC, BrandtH22 approved these changes
lgtm, thank you!

2026-06-08 07:08 UTC, arvidn approved these changes
looks good to me. Please feel free to resolve my comment if you don't think it's worth addressing

2026-06-08 07:08 UTC, arvidn commented on chia/wallet/wallet_rpc_api.py
> +                return response
I think it would be a bit more robust to exit early *before* creating these fields `trade_record`, `transactions` and `unsigned_transactions`.

* it's more efficient, since we don't have to do the work the construct the python objects
* If we add another field in the future, we probably don't want to include it in the `offer_only` path.

2026-06-09 10:55 UTC, ChiaMineJP commented on chia/wallet/wallet_rpc_api.py
> +                return response
Investigated the feasibility and found out that the early return would either re-introduce the unsigned-offer bug that the bug bot mentioned or require duplicating/extracting the signing + persistence logic, which adds more surface area and complexity than the single pop-and-return at the end.

So, I'll mark this as resolved.

2026-06-09 18:39 UTC, merged