Reduce import cycle count
Chia-Network/chia-blockchain pull request #18735
Opened 2024-10-19 18:59 UTC by richardkiss

### Purpose:

See also https://gist.github.com/richardkiss/fbb6228eb55b3917d22dcdb85b8bff9f

This reduces the import cycle count reported by the tool above from 77 to 75 to 66.

### Current Behavior:

### New Behavior:

### Testing Notes:

2024-10-21 21:50 UTC, altendky requested changes
This doesn't look useful but I'll need to look later when I'm at my computer

2024-10-21 22:17 UTC, richardkiss commented
> This doesn't look useful but I'll need to look later when I'm at my computer

My goal is to reduce the number of import cycles, and eventually get to 0. When viewed in the context of that goal, this change is undeniably useful. If you don't think this is a useful goal, let me know why not.

2024-10-22 00:10 UTC, altendky commented
I think we should avoid solely addressing that goal without regard for other aspects of tidiness.  Let's keep working through understanding how the cycles relate to other organizational points and see what we can come up with.

2024-10-22 00:56 UTC, richardkiss commented
> I think we should avoid solely addressing that goal without regard for other aspects of tidiness. Let's keep working through understanding how the cycles relate to other organizational points and see what we can come up with.

To this end, I've put the function that I moved into an existing file instead of creating a new one.

2024-10-22 13:29 UTC, arvidn commented
I also don't see what the value is in reducing these cycles. Are they preventing some other, more tangible, improvements?

2024-10-23 03:37 UTC, richardkiss commented
> I also don't see what the value is in reducing these cycles. Are they preventing some other, more tangible, improvements?

A cycle that crosses (virtual) packages prevents separation of those packages, since (I think) pypi packages can't have mutual dependencies. Or at least, they shouldn't be allowed to IMO because then they are really just one package. Not to mention it could really throw a wrench the package version resolution algorithm.

I believe that cycles also make code more difficult to understand. There are sort of two ways to understand a code-base through its dependency hierarchy: start at the top, high level, and move to the details; or start at the bottom, learn the details, and move up to a higher level understanding. I suppose you can also work your way from the top and bottom and meet in the middle.

A code cycle gives no clues where to start since there is no top and bottom; all files in the cycle must be swapped into your brain simultaneously. Since there is no hierarchy, it is logically one file.

Cycles also prevent the "pull out leaf nodes" strategy from working, since no file in a cycle is a leaf node.

2024-10-23 12:41 UTC, altendky commented on chia/legacy/keyring.py
> +from chia.cmds.passphrase_funcs import prompt_yes_no
This seems strictly worse.  We go from something outside of cmds using the cmds utility module to something outside of cmds using something from a cmds implementation file.  I understand you want to have pinpoint focus on only eliminating cycles.  I just don't think it's good to make the remaining dependencies be even less sensible than before to achieve that goal.  I hope we can take a little bigger picture look here and resolve this in a way that reduces cycles while not making other things distinctly worse.

2024-11-26 19:08 UTC, richardkiss commented
No longer necessary due to another PR that achieves the same goal.

2024-11-26 19:08 UTC, closed without merging