Migrate puzzles away from `load_clvm` to import from chia_puzzles_py
Chia-Network/chia-blockchain pull request #19055
Opened 2024-12-17 16:34 UTC by matt-o-how

### Purpose:

This PR migrates the deployed puzzles from living in this repository to being imported from https://github.com/Chia-Network/chia_puzzles/tree/main

This is a WIP for now

2025-01-07 00:48 UTC, richardkiss commented on chia/_tests/generator/test_rom.py
> +from chia_puzzles_py.programs import CHIALISP_DESERIALISATION, ROM_BOOTSRAP_GENERATOR
is this a spelling error? `ROM_BOOTSTRAP_GENERATOR` vs `...BOOTSRAP...`

2025-01-07 00:48 UTC, richardkiss commented on chia/_tests/generator/test_rom.py
> +from chia_puzzles_py.programs import CHIALISP_DESERIALISATION, ROM_BOOTSRAP_GENERATOR
```suggestion
from chia_puzzles_py.programs import CHIALISP_DESERIALISATION, ROM_BOOTSTRAP_GENERATOR
```

2025-01-07 00:55 UTC, richardkiss commented on chia/wallet/nft_wallet/nft_puzzle_utils.py
> +from __future__ import annotations
I'm curious, what motivated the refactor into this new file?

2025-01-07 01:00 UTC, richardkiss submitted a review, later dismissed
I don't see any obvious problems beyond the one typo. Must have been a huge amount of work!

2025-01-07 12:16 UTC, matt-o-how commented on chia/wallet/nft_wallet/nft_puzzle_utils.py
> +from __future__ import annotations
There was a circular import somewhere if the puzzles stayed in the same place as the utils

2025-01-07 16:51 UTC, arvidn commented on chia/pools/pool_puzzles.py
>  SINGLETON_LAUNCHER_HASH = SINGLETON_LAUNCHER.get_tree_hash()
don't we have `SINGLETON_LAUNCHER_HASH` precomputed?
the question applies to all tree hash computations in here. `POOL_MEMBER_HASH`, `POOL_WAITING_ROOM_HASH`, etc.

2025-01-07 16:51 UTC, arvidn commented on chia/rpc/wallet_rpc_api.py
> +            if cs.coin.puzzle_hash == SINGLETON_LAUNCHER_PUZZLE_HASH:
for a layman, it's not obvious that these are the same

2025-01-07 16:51 UTC, arvidn commented on chia/wallet/nft_wallet/nft_puzzle_utils.py
> +from __future__ import annotations
I take it all of these functions were moved verbatim, right?

2025-01-07 16:51 UTC, arvidn commented on chia/wallet/nft_wallet/ownership_outer_puzzle.py
> +    return NFT_OWNERSHIP_LAYER.curry(NFT_OWNERSHIP_LAYER.get_tree_hash(), current_owner, transfer_program, inner_puzzle)
I imagine we have the tree hash for `NFT_OWNERSHIP_LAYER` precomputed as well. But I suppose fixing these up is outside of the scope of this PR

2025-01-07 16:51 UTC, arvidn commented on chia/wallet/singleton.py
>  SINGLETON_LAUNCHER_PUZZLE_HASH = SINGLETON_LAUNCHER_PUZZLE.get_tree_hash()
I imagine we have these tree hashes pre-computed as well

2025-01-07 16:51 UTC, arvidn commented on chia/wallet/trading/offer.py
>  OFFER_MOD_HASH = OFFER_MOD.get_tree_hash()
and here...

2025-01-07 16:51 UTC, arvidn commented on chia/wallet/util/debug_spend_bundle.py
> +    zero_coin_set = {bytes32(coin.name()) for coin in created if coin.amount == 0}
`Coin.name()` is supposed to return a `bytes32` already.. is it not?

2025-01-07 16:51 UTC, arvidn commented on chia/wallet/vc_wallet/vc_drivers.py
> +REVOCATION_LAYER_HASH: bytes32 = REVOCATION_LAYER.get_tree_hash()
these kinds of constants seem inconsistently updated to use the pre-computed value

2025-01-07 16:57 UTC, matt-o-how commented on chia/wallet/nft_wallet/nft_puzzle_utils.py
> +from __future__ import annotations
Correct

2025-01-07 16:58 UTC, matt-o-how commented on chia/_tests/clvm/test_condition_codes.py
Because the `.clib` file it was referencing was removed (moved to chia-puzzles) and the library is not exported

2025-01-07 17:00 UTC, matt-o-how commented on chia/wallet/util/debug_spend_bundle.py
> +    zero_coin_set = {bytes32(coin.name()) for coin in created if coin.amount == 0}
Strangely the `Coin.name()` returned `bytes` during my testing despite being imported from chia_rs / untouched by me

2025-01-08 09:56 UTC, arvidn reviewed
it seems to me that `STANDARD_BRICK_PUZZLE` (in `vc_drivers.py) as well as `ACS_TRANSFER_PROGRAM` probably should be part of the `chia_puzzles` wheel.

`ACS_TRANSFER_PROGRAM` is currently defined in pure python lists, not even hex, which is a bit unusual.

2025-01-10 10:24 UTC, arvidn requested changes
poetry.lock should be restored (apart from the new `chia-puzzles` dependency)

2025-01-10 13:44 UTC, matt-o-how commented on poetry.lock
> +version = "3.11.10"
Should be resolved now

2025-01-10 13:45 UTC, matt-o-how commented on chia/wallet/singleton.py
>  SINGLETON_LAUNCHER_PUZZLE_HASH = SINGLETON_LAUNCHER_PUZZLE.get_tree_hash()
Resolved now

2025-01-10 13:45 UTC, matt-o-how commented on chia/pools/pool_puzzles.py
>  SINGLETON_LAUNCHER_HASH = SINGLETON_LAUNCHER.get_tree_hash()
Resolved now

2025-01-10 15:21 UTC, arvidn approved these changes, later dismissed

2025-01-17 15:53 UTC, arvidn approved these changes

2025-01-17 16:58 UTC, merged