only copy cert files for init -c
Chia-Network/chia-blockchain pull request #3328
Opened 2021-05-01 15:23 UTC by dkackman

Currently when you `chia init -c <folder>` the code will copy _all_ files in `<folder>` into the config tree. It's a natural step, when copying the certs from one machine to another, to drop them in an existing network share that might contain a bunch of plots or other large files. 

This change only copies files with `crt` or `key` extension.

2021-05-01 18:55 UTC, hoffmang9 requested changes
Looks good but needs a python black run. `pip install black; black chia/cmds/*`

2021-05-01 23:32 UTC, hoffmang9 approved these changes
Nice change and thanks.

2021-05-02 02:07 UTC, dkackman commented
Is this failure worrisome? Error is about operating on a closed database. Seem unlikely it is related but stranger things have happened.

`````
Ubuntu wallet-cc_wallet Test (3.9, ubuntu-latest)
failed 2 hours ago in 9m 8s

2021-05-02 02:12 UTC, hoffmang9 commented
Flakey test. I'm re-running.

2021-05-12 22:34 UTC, wjblanke approved these changes
aok

2021-05-12 22:34 UTC, merged