Configure testnet
Chia-Network/chia-blockchain pull request #3733
Opened 2021-05-04 23:16 UTC by justinengland

this change allows users to swap to the current production testnet "testnet7" without pulling a specific branch. 

And can be easily upgrade to new testnets as needed.

2021-05-04 23:42 UTC, cmmarslender requested changes

2021-05-04 23:42 UTC, cmmarslender commented on chia/cmds/configure.py
> +        config["introducer"]["port"] = int("58444")
to be consistent with the rest?
```suggestion
        config["introducer"]["port"] = int(testnet_port)
```

2021-05-04 23:42 UTC, cmmarslender commented on chia/cmds/configure.py
> +        config["harvester"]["selected_network"] = testnet
I think all these `testnet` values should probably be quoted unless theres a testnet var somewhere I missed at first glance?

2021-05-05 23:43 UTC, aqk commented on chia/cmds/configure.py
> +    if testnet is not None:
Question: is there another config variable that might conflict with this one, e.g. a "mainnet" variable?

2021-05-06 00:10 UTC, aqk approved these changes

2021-05-06 00:11 UTC, cmmarslender approved these changes

2021-05-06 00:19 UTC, merged

2021-05-06 00:42 UTC, atyhieu reviewed
Ok