prints wallet address with pk mnemonic when using 'generate and print'
Chia-Network/chia-blockchain pull request #4383
Opened 2021-05-10 03:14 UTC by sigmarelax

Adding the first wallet address to the terminal output for 'chia keys generate_and_print' is practical for many use-cases. Cold storage wallets can now be outputted and used for storing xch without ever writing the private key to disk

2021-05-10 04:25 UTC, mariano54 approved these changes, later dismissed
Thank you!

2021-05-10 07:50 UTC, Nikolaj-K commented on chia/cmds/keys_funcs.py
> +    root_path = DEFAULT_ROOT_PATH
Seems like you can directly pass the `DEFAULT_ROOT_PATH` one line below.

2021-05-10 07:51 UTC, Nikolaj-K commented on chia/cmds/keys_funcs.py
>      print("Generating private key. Mnemonic (24 secret words):")
```python
print(f"Generating private key. Mnemonic (24 secret words): {mnemonic}")
```

2021-05-10 07:51 UTC, Nikolaj-K commented on chia/cmds/keys_funcs.py
> +            encode_puzzle_hash(create_puzzlehash_for_pk(master_sk_to_wallet_sk(sk, uint32(0)).get_g1()), prefix),
I wouldn't do a computation "this big" inside the print statement.

2021-05-29 01:59 UTC, wjblanke approved these changes, later dismissed
aok

2022-07-06 01:01 UTC, jack60612 requested changes
These are some minor changes that will help your pr align with the rest of our repository better. contact me on keybase if you have any questions, I'm always happy to help.

2022-07-06 01:01 UTC, jack60612 commented on chia/cmds/keys_funcs.py
>  def generate_and_print():
add root_dir here, ex: `def generate_and_print(chia_root: Path)`

2022-08-12 07:30 UTC, jack60612 commented
Ill make the changes i requested into this pr later

2022-11-18 16:43 UTC, closed without merging