second times a charm
Chia-Network/chia-blockchain pull request #6834
Opened 2021-06-17 16:27 UTC by justinengland

changes to allow proper secrets access for upload stages to run during build time. Second attempt, to get around phantom sub module changes in previous git branch.

2021-06-17 16:32 UTC, cmmarslender requested changes

2021-06-17 16:32 UTC, cmmarslender commented on .github/workflows/build-linux-arm64-installer.yml
> +        SECRET: "${{ secrets.test_pypi_password }
```suggestion
        SECRET: "${{ secrets.TEST_PYPI_PASSWORD }
```


Pretty sure theyse are all caps

2021-06-17 16:32 UTC, cmmarslender commented on .github/workflows/build-linux-installer.yml
> +          SECRET: "${{ secrets.test_pypi_password }
```suggestion
          SECRET: "${{ secrets.TEST_PYPI_PASSWORD }
```

2021-06-17 16:36 UTC, cmmarslender submitted a review, later dismissed

2021-06-17 17:24 UTC, cmmarslender commented on .github/workflows/build-linux-arm64-installer.yml
> +        SECRET: "${{ secrets.TEST_PYPI_PASSWORD }
```suggestion
        SECRET: "${{ secrets.TEST_PYPI_PASSWORD }"
```

2021-06-17 17:27 UTC, cmmarslender approved these changes, later dismissed

2021-06-17 18:20 UTC, cmmarslender approved these changes

2021-06-17 18:51 UTC, merged

2021-06-19 08:41 UTC, arvidn commented
This PR landed despite breaking the `build-linux-installer.yml` CI workflow.
I've corrected it here, https://github.com/Chia-Network/chia-blockchain/pull/6862
please review!