[Pools.dev]add post /partial and /farmer header
Chia-Network/chia-blockchain pull request #6957
Opened 2021-06-24 08:26 UTC by lpf763827726

2021-06-24 08:29 UTC, lpf763827726 commented
default it wasn't application/json, so when i post to server i always reprot **post 422**, please check it

2021-06-24 18:01 UTC, xdustinface requested changes
See the two nits which which would cause trouble on CI.

2021-06-25 01:29 UTC, mariano54 approved these changes

2021-06-25 15:58 UTC, xdustinface approved these changes

2021-06-28 07:32 UTC, merged