Information about proof found plots in logs
Chia-Network/chia-blockchain pull request #7000
Opened 2021-06-27 13:57 UTC by alek-sai

Appears in logs on proofs messages like:
```
2021-06-27T20:54:45.822 harvester chia.harvester.harvester: DEBUG    ✅ Proofs generated by: ['plot-k25-2021-06-26-16-56-edf0ce8eaf528fbb290f8d3fb8f17ab74b905c85cfaffbe91b192eb59054ae1f.plot (P2: txch1tt7j3lhxtpvpsrll643cftum2m89krkmdaec4yhtz7rlmh7x9dzsjn9esl)']
```

I'm proposing this useful info imo on DEBUG level of logging, but if it can be considered as INFO, can change it.

2021-06-29 12:49 UTC, mariano54 approved these changes
LGTM! any rationale why put it in DEBUG and not INFO? Is it to avoid breaking current tooling which reads log file?

2021-06-29 14:04 UTC, alek-sai commented
@mariano54 you are right, must be info. Debug isn't having any sense.

2021-06-29 14:15 UTC, alek-sai commented
I didn't understand first part of your sentence btw, I'm trying to find those lint mistakes I possibly made, but can't found any related to code I've added. I'm not so familiar with LGTM, can you point me if possible?

2021-06-29 17:01 UTC, alek-sai commented
Thank you for collaboration and lgtm acronym clarifying, Gene! I've checked lgtm.com and seems like no issues https://lgtm.com/projects/g/Chia-Network/chia-blockchain/rev/pr-367609de987007fc6e03b7bd431af9f521fca680

2021-06-30 20:28 UTC, alek-sai commented
@mariano54 @hoffmang9 guys, should I still do something or to relax and wait? happy phase 2 btw :)

2021-07-01 01:05 UTC, mariano54 requested changes
Also, i think you need to start again from the main branch, looks like some tests are failing

2021-07-01 01:05 UTC, mariano54 commented on chia/harvester/harvester_api.py
> +        config = load_config(DEFAULT_ROOT_PATH, "config.yaml")
We don't want to load the config on every run. Use the harvester config: `self.harvester.config`, or even better just print out the puzzle hash. The harvester knows nothing about address encodings

2021-07-01 09:14 UTC, closed without merging