Update reconnect_task.py
Chia-Network/chia-blockchain pull request #7085
Opened 2021-07-01 11:09 UTC by zhoushunping

Domain name resolution should be performed again when reconnecting

2021-07-01 11:28 UTC, zhoushunping commented
When the primary node is unavailable, it will automatically switch to the standby node according to the new address resolved by the domain name

2021-07-01 14:32 UTC, arvidn requested changes

2021-07-01 14:32 UTC, arvidn commented on chia/server/reconnect_task.py
> +                    host = socket.gethostbyname(peer_info_arg.host)
this is a blocking call, that may lock up all other tasks. This has to be async. We use an async DNS library in other parts of the code

2021-07-02 03:12 UTC, zhoushunping reviewed
We use an async DNS library for a non-blocking call

2021-07-02 06:52 UTC, zhoushunping reviewed
finished

2021-07-05 15:15 UTC, duongxuantuan154 approved these changes
- [ ]

2024-03-20 17:29 UTC, emlowe commented
I believe this PR needs to have some substantial updates as the current code has moved. Closing PR. It can be re-opened if updated

2024-03-20 17:29 UTC, closed without merging