Verify weight
Chia-Network/chia-blockchain pull request #73
Opened 2020-01-15 05:33 UTC by AWice

2020-01-15 06:58 UTC, mariano54 requested changes
This code prefers Blockchain blocks over the new chain's blocks, which means it will not get the correct difficulty in a longer reorg. 

Also it's not checking proofs of time.

At the very least it needs to calculate challenges, ips, and check proof of time for each block. Perhaps we should also check prev_header_hash in the header. 

Finally, we should add tests to make sure it's doing these things correctly.

2020-01-27 03:58 UTC, mariano54 commented
Can you make the PR into 1.4 instead of 1.3? Hard to see the changes here.

2020-01-28 07:14 UTC, mariano54 requested changes
Can you also write a test or two for this function? You can model it after the reorg tests in blockchain.py. And try running it with the testnet chain to see how long it takes? I was just thinking that if someone closes the node while this is running, it won't stop (which is problematic if it takes more than 15 minutes). We could check in each execution of the loop whether the node has closed. I can help you with this if you want, you have to pass in a callback from full node into the verify_weight function. 

Another potential optimization is to only do like 100 headers at a time, to reduce memory requirements, but we can probably do that later.

2020-02-05 07:50 UTC, AWice commented on src/blockchain.py
> +        def get_header_block_from_height_or_hash(
I thought to combine them initially, but sometimes you only want difficulty in the recursive calls.  So I think they would be split.

2020-02-25 11:44 UTC, mariano54 commented
Please change base branch to 1.5.

Also we should use the pre_validation code that straya added to avoid having to validate all headers twice. I'm kind of hesitant of merging this at this point, since it will make syncing really slow, and we will be merging integration branch relatively soon (which has many changes to the format which impact this PR).

2020-05-08 04:05 UTC, mariano54 commented
Working on including part of this PR into to ms.sync branch

2020-05-13 05:55 UTC, mariano54 commented
This is replaced by: https://github.com/Chia-Network/chia-blockchain/pull/218

2020-05-13 05:55 UTC, closed without merging