add ids to the return response of start_plotting
Chia-Network/chia-blockchain pull request #7416
Opened 2021-07-12 15:37 UTC by dkackman

This is a simple addition to collect the id's of plots as they are queued and return them with the response. Makes it a titch easier on the caller to manage the work.

2021-07-12 16:36 UTC, dkackman commented
I fixed the one black message (trailing white space) related to my change. The default run of black reformatted some other stuff too, which I did not include. I can include those if need be.

2021-07-20 18:36 UTC, aqk requested changes
Hi @dkackman, I think if you accept the suggested change, we can take your PR

2021-07-20 18:36 UTC, aqk commented on chia/daemon/server.py
> +        ids : List[str] = []
```suggestion
        ids: List[str] = []
```

2021-07-21 11:27 UTC, dkackman commented
> Hi @dkackman, I think if you accept the suggested change, we can take your PR

Done

2021-09-06 16:57 UTC, dkackman commented
hiya @aqk - I accepted the changes but it's blocked on what looks like a broken build action. Could you take a look and unstick this one?

2021-09-06 17:02 UTC, jack60612 commented
> hiya @aqk - I accepted the changes but it's blocked on what looks like an unrelated broken build action. Could you take a look and unstick this one?

i got it

2021-09-06 17:19 UTC, hoffmang9 commented
I'm afraid it may be to old to just rerun the test. Can you force push or make a trivial change to rerun them @dkackman ?

2021-09-06 23:19 UTC, dkackman commented
> I'm afraid it may be to old to just rerun the test. Can you force push or make a trivial change to rerun them @dkackman ?

Done

2021-09-08 23:23 UTC, dkackman commented
Hey guys. Anything more needed in this one?

2021-09-08 23:24 UTC, jack60612 commented
> Hey guys. Anything more needed in this one?

Sometimes greatness comes naturally

2021-09-09 00:13 UTC, emlowe approved these changes
seems ok to me

2021-09-14 17:38 UTC, merged