regenerate workflow files. fix test_hint_store.py
Chia-Network/chia-blockchain pull request #8725
Opened 2021-10-05 14:55 UTC by arvidn

2021-10-05 16:08 UTC, Yostra submitted a review, later dismissed

2021-10-05 16:24 UTC, xdustinface requested changes
Let's maybe just rebase this one after https://github.com/Chia-Network/chia-blockchain/pull/8728 and then drop `test_hint_store` [here](https://github.com/Chia-Network/chia-blockchain/pull/8728/commits/1ddc5e25ba7f6f9eb4dd227c6e3cc07bbfbc537c#diff-6c74ae58ee828a4e86eac9d5b37b43e8fbc5c3354fc26ca7235c5fab93cdbcefR5)?

2021-10-08 07:08 UTC, arvidn commented
I think this is a minimal step to fix the hint store test and enable it in CI. I think it's a step in the right direction and can land independently.

2021-10-13 21:08 UTC, xdustinface submitted a review, later dismissed

2021-10-13 21:59 UTC, xdustinface approved these changes

2021-10-13 23:05 UTC, merged