move test utility DBConnection out of test_coin_store and into its own file
Chia-Network/chia-blockchain pull request #8756
Opened 2021-10-07 14:49 UTC by arvidn

2021-10-07 15:12 UTC, xdustinface requested changes
Requires adjustment here too https://github.com/Chia-Network/chia-blockchain/blob/5bcfcc1f4fbbdac0c1e7c365594bdfe15126e528/tests/core/full_node/test_hint_store.py#L12 and i would rename it to `TempDatabase` or something similar to make clear its not persistent and also because it returns a `DBWrapper`, not a connection.

2021-10-07 15:31 UTC, arvidn commented
I'd prefer to not couple this change with a rename as well. I don't have a strong opinion about the name, but I'd like to keep this PR small and uncontroversial as I have more patches waiting on it.

2021-10-07 15:32 UTC, xdustinface approved these changes

2021-10-08 13:11 UTC, wjblanke approved these changes
aok

2021-10-08 13:11 UTC, merged