pre-commit: Add a new hook to run `isort`
Chia-Network/chia-blockchain pull request #8827
Opened 2021-10-14 15:36 UTC by xdustinface

Inspired by https://github.com/Chia-Network/chia-blockchain/pull/8821#discussion_r729079099

2021-10-14 16:18 UTC, jack60612 submitted a review, later dismissed
Lgtm

2021-10-14 23:39 UTC, altendky approved these changes
Looks enough like https://github.com/twisted/twisted/blob/0e54ecabe83e2f2dc75a9ac6c765e891e2f9381e/.pre-commit-config.yaml#L8-L11 for me.  I see it did in fact run in CI and pass at https://github.com/Chia-Network/chia-blockchain/pull/8827/checks?check_run_id=3896686769#step:4:81.

I don't know etiquette related to imposing new rules here or for massive (even if not major) changes like this so I would expect some discussion or somesuch.  But, it's good for me.

Maybe it would be nice to ban relative imports?  We have a few scattered around and it seems to me the sort of thing you generally ought to either always do or never do but this could make sense as a separate PR anyways.

2021-10-14 23:45 UTC, hoffmang9 commented
In the past it's been me making these sorts of changes. I'd generally post on Keybase soliciting any objections. One note is that we need to update CONTRIBUTING to add this point.

2021-10-14 23:52 UTC, altendky requested changes
To formalize @hoffmang9's comment, here's a change request.

2021-10-15 17:18 UTC, altendky submitted a review, later dismissed

2022-01-26 02:43 UTC, xdustinface commented
@altendky I added added the workaround for the pre-commit-isort-install issue, see 76907da4279b75377a0e83d9e37d617de3a810b3 + your commits to exclude the currently unsorted files + i rebased on `main` and adjusted the ignore list in 71d6e3a.

2022-01-27 02:26 UTC, altendky submitted a review, later dismissed
Close.  I should have remembered to add https://github.com/xdustinface/chia-blockchain/pull/3 before.  Basically, clear the ignore list, run that command, copy paste back in as the ignore list to update it.

Thanks for keeping at this.

2022-01-27 02:26 UTC, altendky commented on setup.py
> +    "isort",
Apparently we need a dsort too...  `:]`  (dependency sort)

2022-01-27 02:26 UTC, altendky commented on setup.py
> +    "isort",
(no, don't change anything here.  just noting pre-existing unsorted deps...)

2022-01-27 07:30 UTC, xdustinface commented
I regenerated the list already, again see 71d6e3a in case you missed it in my last comment. About adding that command as comment, Why should we ever need to regenerate that list? All i want to see there is entries getting dropped tbh 😄

2022-01-28 04:30 UTC, altendky approved these changes, later dismissed
Thanks again!

2022-02-01 16:03 UTC, xdustinface commented
Rebased

2022-02-01 18:24 UTC, altendky submitted a review, later dismissed

2022-02-15 15:28 UTC, wjblanke approved these changes
aok

2022-02-15 15:28 UTC, merged