Sqlite context mgr
Chia-Network/chia-blockchain pull request #9582
Opened 2021-12-15 22:59 UTC by arvidn

2021-12-16 10:31 UTC, arvidn commented
I'm having second thoughts about using `async for` to stream results back. I suspect that might contributing to slowing this down. It might add more context switches for instance.

2021-12-16 18:22 UTC, altendky requested changes
Some tweaks, but otherwise good.  If you remove the async iteration, that makes it a bit more focused of a PR so...  either way.

I did do a bit of benchmarking myself and found about a 1% apparent slow down though there was 2-3% stddev on the actual runtime of either leaving me a bit skeptical of the performance importance.  Though, I didn't dig out how to conclude if there was a statistically significant difference or not.

https://gist.github.com/altendky/6b7b564f60ed8a4cc1c7e24945f6b45a

https://docs.google.com/spreadsheets/d/1ygeCnuYJA7IfI5A_BMi-6H99_sFAyUetlWAUo-Rnz1M/edit#gid=0



| before | after |  
| -- | -- | -- |
| 274.3248 | 292.738 | 6.7%
| 271.7372 | 274.6443 | 1.1%
| 288.1356 | 291.053 | 1.0%
| 287.8522 | 291.7024 | 1.3%
| 292.1706 | 291.653 | -0.2%
| 291.8701 | 292.7326 | 0.3%
| 288.388 | 290.962 | 0.9%
| 288.0278 | 293.2307 | 1.8%
|  |   |  
| 285.3132875 | 289.8395 |  
| 7.803895491 | 6.195129856 |  
| 2.7% | 2.1% |  

2021-12-16 19:43 UTC, arvidn commented on chia/full_node/block_height_map.py
> +                    return self
yeah. the reason I did that was that it still feels strange to me that variables declared in an inner scope still exist outside of the scope..

2021-12-16 19:44 UTC, arvidn commented on chia/full_node/block_store.py
> -            await cursor_1.close()
I modeled this after the first example from the docs: https://aiosqlite.omnilib.dev/en/stable/index.html

```
await db.execute("INSERT INTO some_table ...")
```

2021-12-16 19:45 UTC, arvidn commented on chia/full_node/block_store.py
> +            return ret
I think I'll back-out `async for` from this patch for now though

2021-12-16 21:44 UTC, arvidn commented
@altendky I dropped all the `async for` and incorporated your suggested changes. The new timings are closer (but I just ran the new ones once).

This commit:

block_store:
```
version 1
89.6409s, add_full_block
53.2567s, get_full_block
5.2159s, get_full_block_bytes
51.1661s, get_full_blocks_at
5.8824s, get_block_records_by_hash
52.6979s, get_blocks_by_hash
7.1451s, get_block_record
0.6540s, get_block_records_in_range
0.0053s, get_block_records_close_to_peak
4.6177s, get_block_record
66.4469s, get_random_not_compactified
all tests completed in 336.7288s
database size: 2418.156 MB
version 2
44.0412s, add_full_block
52.3799s, get_full_block
5.0736s, get_full_block_bytes
50.2342s, get_full_blocks_at
6.3605s, get_block_records_by_hash
53.0350s, get_blocks_by_hash
6.6490s, get_block_record
0.7128s, get_block_records_in_range
0.0061s, get_block_records_close_to_peak
4.5579s, get_block_record
88.9816s, get_random_not_compactified
all tests completed in 312.0317s
database size: 357.474 MB
```

coin_store:
```
version 1
Building database
52.9241s, MOSTLY ADDITIONS additions: 400400.0 removals: 20000.0
7.6849s, MOSTLY REMOVALS additions: 600 removals: 140000
72.3118s, FULLBLOCKS additions: 400400 removals: 400000
1.4111s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
68.3960s, GET RECORDS BY NAMES without spent 200 lookups found 20641 coins in total
24.7959s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
all tests completed in 227.5239s
database size: 638.095 MB
version 2
Building database
45.5893s, MOSTLY ADDITIONS additions: 400400.0 removals: 20000.0
7.9858s, MOSTLY REMOVALS additions: 600 removals: 140000
64.8043s, FULLBLOCKS additions: 400400 removals: 400000
2.1198s, GET RECORDS BY NAMES with spent 200 lookups found 40000 coins in total
50.4896s, GET RECORDS BY NAMES without spent 200 lookups found 20693 coins in total
23.2696s, GET COINS REMOVED AT HEIGHT 800 blocks, found 580000 coins in total
all tests completed in 194.2584s
database size: 353.620 MB
```

2021-12-17 01:33 UTC, altendky commented on chia/full_node/block_height_map.py
> +                    return self
It's not a scope.  `:]`  You get scopes for a module, class (though these are... weird), function, comprehensions...  and lambdas i guess.

2021-12-19 01:41 UTC, altendky commented on chia/full_node/block_store.py
> +                heights.append(int(row[0]))
https://github.com/Chia-Network/chia-blockchain/runs/4571820373?check_suite_focus=true

```suggestion
        heights = [int(row[0]) for row in rows]
```

2021-12-19 21:04 UTC, altendky approved these changes
I would generally like to see the minimal amount of code in the context blocks as possible so resources get released quickly.  As always, happy to chat about it.  But, I don't think the cases here are significant issues so not getting hung up on that now.

There were some timeouts on the tests for the plotting directory on Ubuntu but the timeout rate on this PR and main seem the same as of running them both now.  I guess I'll have to dig into that separately.  I haven't seen the hangs locally yet.

Thanks for the context management!

2021-12-20 18:39 UTC, merged

2021-12-20 20:42 UTC, arvidn commented
Although that's probably a good rule of thumb, when it comes to async processes, I don't think it's necessarily always true. For instance, perhaps the exiting of the context will synchronize (and wait for) some background task completing. If you can defer this synchronization, you may increase concurrency.

But perhaps there aren't any examples of that in the real world.