Add announcement to create signed transaction
Chia-Network/chia-blockchain pull request #9735
Opened 2022-01-05 18:25 UTC by jack60612

2022-01-05 23:06 UTC, mariano54 requested changes

2022-01-05 23:06 UTC, mariano54 commented on chia/rpc/wallet_rpc_api.py
> +        coin_announcements = None
Can we use a type annotation here?

2022-01-05 23:06 UTC, mariano54 commented on chia/rpc/wallet_rpc_client.py
> +        coin_announcements: bytes32 = None,
This should be List[bytes32] right?

2022-01-06 00:04 UTC, jack60612 commented on chia/rpc/wallet_rpc_api.py
> +        coin_announcements = None
Added

2022-01-06 00:14 UTC, jack60612 commented on chia/rpc/wallet_rpc_client.py
> +        coin_announcements: bytes32 = None,
Fixed

2022-01-06 12:39 UTC, mariano54 commented
A few more comments:
- Undo changes to files not relevant to change: `.flake8`, `.isort.cfg`.
- Add a test to `test_full_node_rpc.py` to make sure it is working
- Fix lint until all the checks are green

2022-01-06 13:52 UTC, mariano54 commented on chia/rpc/wallet_rpc_api.py
> +        coin_announcements: Set[bytes32] = None
I think you will have to change this to Optional[Set[bytes32]] because None is not a Set. 
Or initialize to set()

2022-01-06 16:03 UTC, mariano54 approved these changes, later dismissed

2022-01-07 13:15 UTC, mariano54 approved these changes

2022-01-07 13:16 UTC, merged