Set reserved cores to 0
Chia-Network/chia-blockchain pull request #9790
Opened 2022-01-12 16:24 UTC by mariano54

The sync speed benefits when switching to zero are significant, and many users are switching to it. This is especially clear in machines with not many cores like the RPI. 

RPI DUSTSTORM1  6:15 -> 5:08
RPI TRANSACTION_START: 0:40 -> 0:33

Data can be seen here: 
https://github.com/neurosis69/chia-sync-data

The initial reason for having 2 here was that linux was lagging for some people during sync. However this is anectdotal evidence and might not be related to this change, as this was a long time ago there were many bugs present in past versions. 

Furthermore, as pointed out by @altendky operating systems should not freeze even when under full CPU load. Chia sync also currently does not take advantage of all CPUs even after this change.

2022-01-12 16:38 UTC, hoffmang9 submitted a review, later dismissed
AOK

2022-01-12 16:42 UTC, altendky requested changes
There are defaults in the code reading this for when this is not present.  They should be updated as well.  Also to make sure it was considered, there's a separate setting for the wallet process pool.

The config should all be centralized and then we could write a test to check that the static default config file (with comments) matches the defaults for when the value is not specified.  But that is...  a whole other thing.

2022-01-12 17:38 UTC, neurosis69 commented
> 
> RPI DUSTSTORM1 6:15 -> 5:08 
> RPI TRANSACTION_START: 0:40 -> 0:33
> 

The mentioned times here compare between my test scenarios AUTOTEST1 with AUTOTEST5.
Just please be aware, that for the test scenario AUTOTEST5 in addition to the cpu core change, I also droped all indexes from table coin_records. The missing indexes will be recreated automatically after the next node restart.

On RPI the drop of the Coin Record Indexes only (AUTOTEST3) reduced sync time from 6:15 -> 5:30.

2022-01-12 18:31 UTC, mariano54 commented
> 

Thank you! I will fix that.

2022-01-12 18:31 UTC, mariano54 commented
> > RPI DUSTSTORM1 6:15 -> 5:08
> > RPI TRANSACTION_START: 0:40 -> 0:33
> 
> The mentioned times here compare between my test scenarios AUTOTEST1 and AUTOTEST5. Just please be aware, that for the test scenario AUTOTEST5 in addition to the cpu core change, I also droped all indexes from table coin_records. The missing indexes will be recreated automatically after the next node restart.
> 
> On RPI the drop of the Coin Record Indexes only (AUTOTEST3) reduced sync time from 6:15 -> 5:30.

Thank you! I will fix that.

2022-01-15 19:04 UTC, altendky submitted a review, later dismissed
This lost the wallet reserved cores default in code at some point.  Either that should be added back or the change to the default config file should be removed.

2022-01-16 01:36 UTC, mariano54 commented
> This lost the wallet reserved cores default in code at some point. Either that should be added back or the change to the default config file should be removed.

The wallet was completely changed with the new update so maybe it's not even relevant. ill check.

2022-01-20 19:17 UTC, altendky approved these changes
I think it might be a good idea to consider setting reduced priority for these processes.  I don't expect this will lock anyone out of their systems though.  I haven't had any significant issues that I remember on my Pi while running with four cores used.

2022-01-21 15:00 UTC, mariano54 commented
Waiting on merge @wjblanke @emlowe

2022-01-24 05:52 UTC, merged

2022-01-24 05:52 UTC, wjblanke commented
I'll merge this since we are releasing in beta but we may need to swap the preference names if we have to override the 0 setting if an issue is found.

2022-01-24 15:08 UTC, altendky commented
@wjblanke i'm not sure what you mean by "swap the preference names"?  I understand your concern that 0 may cause some people trouble.