error handling for create store
Chia-Network/chia-blockchain pull request #9926
Opened 2022-01-24 12:46 UTC by almogdepaz

2022-01-25 13:30 UTC, altendky requested changes
Yes, if there's a resource to be managed make a context manager.  It looks like it might be able to handle all the existing  `try`/`except` plus the client close in a finally.

2022-01-25 13:30 UTC, altendky commented on chia/rpc/wallet_rpc_api.py
> +            return {"success": False, "error": str(e)}
Doesn't the framework handle this such that just a bare `raise` would be fine after logging?  Or maybe the framework takes care of the logging as well?  The log should have the traceback.

2022-01-25 13:30 UTC, altendky commented on chia/rpc/wallet_rpc_api.py
> +            "success": True,
Doesn't the framework add this?

2022-01-25 13:30 UTC, altendky commented on chia/rpc/wallet_rpc_client.py
> +        #     return response["error"]
```suggestion
```

2022-01-25 13:30 UTC, altendky commented on chia/rpc/data_layer_rpc_api.py
> +log = logging.getLogger(__name__)
Don't we generally pass in loggers rather than creating them locally?  Also, the changes here look all unused?

2022-01-25 13:30 UTC, altendky commented on chia/data_layer/data_store.py
> +                raise Exception("tree id not in store")
Unless the ID can be considered semi-private?

```suggestion
                raise Exception(f"tree id not in store: {tree_id.hex()}")
```

2022-01-25 13:30 UTC, altendky commented on chia/data_layer/data_store.py
> +                raise Exception("tree id not in store")
Unless the ID can be considered semi-private?

```suggestion
                raise Exception(f"tree id not in store: {tree_id.hex()}")
```

2022-01-25 13:30 UTC, altendky commented on chia/rpc/data_layer_rpc_client.py
> +    async def create_data_store(self) -> Optional[Dict[str, Any]]:
When would this return `None`?

https://github.com/Chia-Network/chia-blockchain/blob/94e961f41019be9a4c3a1154623a4a56c5708711/chia/rpc/data_layer_rpc_api.py#L59-L63

https://github.com/Chia-Network/chia-blockchain/blob/94e961f41019be9a4c3a1154623a4a56c5708711/chia/rpc/rpc_client.py#L44-L50

```suggestion
    async def create_data_store(self) -> Dict[str, Any]:
```

2022-01-25 21:18 UTC, emlowe requested changes

2022-01-25 21:18 UTC, emlowe commented on chia/cmds/data_funcs.py
>      store_id_bytes = bytes32(hexstr_to_bytes(store_id))
I believe we prefer `bytes32.from_hexstr()` over `bytes32(hexstr_to_bytes())` - several instances here

2022-01-26 10:48 UTC, arvidn commented
with the `finally` block I think using a context manager is even more called for. I made this PR against your PR: https://github.com/Chia-Network/chia-blockchain/pull/9956

2022-01-26 16:43 UTC, altendky commented
@arvidn, I generally prefer [the `@contextmanager` decorator](https://docs.python.org/3.10/library/contextlib.html#contextlib.contextmanager).  Was there a specific need for the class/method approach here?  Regardless, your context manager does move it all to a single location which is the real value.  Thanks!  I will add to the todo list to consider consuming the rest of the remaining `try`/`except` into either this context manager or another that uses it.

2022-01-26 16:57 UTC, altendky approved these changes

2022-01-26 17:04 UTC, emlowe approved these changes

2022-01-26 20:17 UTC, merged